### DISCUSSION TITLE
Change staticcheck severity to warning

### DISCUSSION THREAD

**Discussion by DONSA** [golangci/golangci-lint#1853] [Q&A] [answered]
Hi,

I deprecated some methods in my code and now the linter is complaining:
```
internal/graphql/resolver.go:1318:23: SA1019: measurement.TotalWeight is deprecated: It will be deleted (staticcheck)
```
I think this should be a warning, not an error. There's any way to change it?

I tried this without success since the command is still returning exit code 1:
```
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - staticcheck
      severity: warning
```

**Comment by ldez** [comment, marked as answer]
Hi,

The severity configuration allows handling a dedicated field, called `severity`,  in some output format 

The severity configuration doesn't change the exit code.

I recommend adding an exclude rule:

```yaml
issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019: measurement.TotalWeightStore is deprecated"
```
