### DISCUSSION TITLE
How to keep the linters in the config file updated for the new versions?

### DISCUSSION THREAD

**Discussion by frederikhors** [golangci/golangci-lint#1887] [Q&A] [answered]
I'm using the below config file.

```yaml
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    # - exhaustivestruct
    - exportloopref
    - forbidigo
    - funlen
    # - gci
    - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
# ... and so on
```

as you can see I'm disabling some of them.

The question: how can I keep this file updated with the new linters that are added in the new versions?

Is there any way to know which linter has been added that isn't on this list?
