### DISCUSSION TITLE
[Linter Funlen] Ignore some specific funtions

### DISCUSSION THREAD

**Discussion by dharmjit** [golangci/golangci-lint#1895] [Q&A] [answered]
Hello, 

Is it possible to skip some functions for `funlen` linting. As there are few functions in my code where the no. of lines/statements are more than what is configured and we will be doing the refactor later.

Thanks

**Comment by ldez** [comment, marked as answer]
Hello,

You have 2 solutions:

- use `//nolint:funlen` on those functions
```go
//nolint:funlen // explanation
func MyFunction()  {
	// ...
}
```
- define an `exclude-rules`  in `.golangci.yml`
```yml

issues:
  exclude-rules:
    - path: path/to/my/file.go
      text: "Function 'MyFunction' is too long"
```
