### DISCUSSION TITLE
Is there a way to disable a single revive's rule?

### DISCUSSION THREAD

**Discussion by frederikhors** [golangci/golangci-lint#2009] [Q&A] [answered]
I'm using golangci-lint 1.40.1.

Is there a way to disable a single revive's rule?

Such as:

```yaml
linters-settings:
  revive:
    rules:
      - name: exported
        deactivate: true
```

This doesn't work right now.
