### DISCUSSION TITLE
How to make pre-commit work

### DISCUSSION THREAD

**Discussion by sarnikowski** [golangci/golangci-lint#2132] [Q&A]
Hello

I've been trying to get the pre-commit hook to work, but I keep getting the following error:
```
- hook id: golangci-lint
- exit code: 5

level=error msg="Running error: context loading failed: no go files to analyze"
```
This error only happens when I have actually staged `.go` files, which is why the error message is a bit puzzling (i am using this hook in a polyglot monorepo).

Relevant section of my pre-commit config:
```yaml
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.41.1
    hooks:
      -   id: golangci-lint
```
Any pointers or ideas would be much appreciated.
