### DISCUSSION TITLE
Revive settings in config not being honored

### DISCUSSION THREAD

**Discussion by azeemshaikh38** [golangci/golangci-lint#2144] [Q&A] [answered]
Hi my golangci-lint config file looks this:

```
linters:
  disable-all: true
  enable:
    ...
    - revive
    ...
linters-settings:
  ...
  revive:
    ignore-generated-header: true
    severity: warning
    enableAllRules: true
    rules:
    - name: package-comments
    - name: exported
  ...
```

But the revive rules (specifically `package-names` and `exported`) don't seem to be running (I expect a failure but see no warn/errors). Could someone tell me if my config is wrong and if so how I should fix it?
