### DISCUSSION TITLE
How to find docs for older version like v1.30.0?

### DISCUSSION THREAD

**Discussion by gy95** [golangci/golangci-lint#2181] [Q&A] [answered]
When i want to enable `gosec` linter, i use this below to want to detect only G601, but seems not to work.
```
linters-settings:
  gosec:
    include:
      - G601
```
 [golangci-lint.run](https://golangci-lint.run/usage/linters/) website docs is maybe for latest vesions. How to find reference for v1.30.0?
BTW, the slack link of official website has expired, may be need a update.
