### DISCUSSION TITLE
How to enable fieldalignment?

### DISCUSSION THREAD

**Discussion by choleraehyq** [golangci/golangci-lint#2194] [Q&A] [answered]
After I upgrade golangci-lint, it warns me that "The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.". But I haven't found a way to enable it. Both 
```
linter-settings:
  govet:
    enable:
      - fieldalignment
```
and 
```
linters:
  enable:
    - fieldalignment
```
don't work.

**Comment by ldez** [comment, marked as answer]
Hello,

You have to enable `govet`:

```yml
linters-settings:
  govet:
    enable:
      - fieldalignment

linters:
  enable:
    - govet
```

**Reply by choleraehyq** [reply]
I've done some debug works, seems GovetSettings.Enable is an empty slice with this config file. But I haven't found out why.

**Reply by choleraehyq** [reply]
I see. It should be "linters-settings" rather than "linter-settings".

**Comment by choleraehyq** [comment]
@ldez 
```
linters:
  enable:
    - govet
    - goimports
    - prealloc
    - unconvert
  disable:
    - errcheck
    - unused
    - deadcode

linter-settings:
  govet:
    enable:
      - fieldalignment
```
I run `golangci-lint run` with this .golangci.yml, but `fieldalignment` is still not be triggered. Running `fieldalignment ./...` directly is successful as expected.

My golangci-lint version is `golangci-lint has version v1.42.0 built from (unknown, mod sum: "h1:hqf1zo6zY3GKGjjBk3ttdH22tGwF6ZRpk6j6xyJmE8I=") on (unknown)` .
