### DISCUSSION TITLE
Is `golangci-lint` detecting my auto-generated files? Is there a FAQ or docs?

### DISCUSSION THREAD

**Discussion by frederikhors** [golangci/golangci-lint#2233] [Q&A] [answered]
I'm using [gqlgen](https://github.com/99designs/gqlgen) and I have many big auto-generated files.

Each `golangci-lint` run is slow.

Is `golangci-lint` detecting my auto-generated files? Is there a FAQ or docs?

I wanna exclude those files from scanning.

**Comment by ldez** [comment, marked as answer]
Hello,

you can use `skip-dirs` or `skip-files`.

https://golangci-lint.run/usage/configuration/#config-file

```yml
run:

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs:
    - src/external_libs
    - autogenerated_by_my_lib

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-files:
    - ".*\\.my\\.go$"
    - lib/bad.go
```
