### DISCUSSION TITLE
new-from-rev behaving differently locally & in github action?

### DISCUSSION THREAD

**Discussion by natefinch** [golangci/golangci-lint#2256] [Q&A] [answered]
I have a config file golangci-pr.toml in my repo that sets `new-from-rev="main"` 

When I run `golangci-lint run -c=.golangci-pr.toml` on my machine, after pulling main and my branch, it runs with no issues reported.

I have a github action, using the golangci-lint github action, with the configuration below, which reports a bunch of issues in files that aren't a part of this PR.  I'm not sure what's going on.

I'd like to be able to run the same command in the action and locally to make sure it's easy to get the same results... but I'm not getting the same results. :( 

Any ideas?

```
name: Golangci-lint PR
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: lint-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.42.1

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: -c=.golangci-pr.toml
```

**Comment by ldez** [comment]
I think the answer is here: https://github.com/golangci/golangci-lint/issues/1088#issuecomment-801540792

**Comment by natefinch** [comment]
Ahh shallow clone... Lemme see if i can twiddle with that.

**Comment by natefinch** [comment, marked as answer]
ok, yeah, the fix is to set fetch-depth on the checkout to 0, which gets everything rather than just the last commit:

```
      - uses: actions/checkout@v2
        with: 
          # this gets us all the branch commits, which new-from-rev needs
          fetch-depth: 0
```

And you need to make sure you use new-from-rev="origin/main" not just "main"..... for reasons that are beyond my comprehension :)
