### DISCUSSION TITLE
Why this config doesn't exclude these files?

### DISCUSSION THREAD

**Discussion by frederikhors** [golangci/golangci-lint#2284] [Q&A] [answered]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I'm using a config like this:

```yaml
issues:
  exclude-rules:
    - path: internal/custom/dir/*.custom.go
      linters:
        - wrapcheck
```

but it doesn't work.

It works if I use this instead:

```yaml
issues:
  exclude-rules:
    - path: .custom.go
      linters:
        - wrapcheck
```

Why?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z
```

</details>

### Go environment

<details>

```console
$ go version && go env
# go version go1.17.2 windows/amd64
```

</details>

**Comment by ldez** [comment, marked as answer]
Hello,

the `path` is a regex field, not a glob field.
so `*` cannot be used alone.

The right configuration:
```yml
linters:
  disable-all: true
  enable:
    - wrapcheck

issues:
  exclude-rules:
    - path: internal/custom/dir/(.*).custom.go
      linters:
        - wrapcheck
```
