### DISCUSSION TITLE
skip-dirs

### DISCUSSION THREAD

**Discussion by EvanLjp** [golangci/golangci-lint#2378] [Q&A] [answered]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

1. I install golangci-lint with `curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(GO_PATH)/bin v1.43.0` commands in github workflows
4. the external dir was skipped on macos or linux, but it doesn't work on windows.

```
  skip-dirs:
    - (^|/)vendor($|/)
    - (^|/)external($|/)
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
v1.43.0
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

```
# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  skip-dirs:
    - (^|/)vendor($|/)
    - (^|/)external($|/)
    # todo delete or polish packages
    - (^|/)plugins/input/input_wineventlog($|/)

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: false

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  skip-files:
    - plugins/input/journal/unit.go
    - plugins/input/journal/follow.go

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  modules-download-mode: readonly

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  # all available settings of specific linters
linters-settings:
  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    includes:
    excludes:
      - G204
  govet:
    # report about shadowed variables
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    enable-all: true
    # TODO: Enable this and fix the alignment issues.
    disable:
      - fieldalignment

  revive:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/alibaba/ilogtail

  misspell:
    locale: US
    ignore-words:

linters:
  disable:
    - errcheck
  enable:
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused


issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: .*_test.go
      linters:
        - errcheck
        - gosec
    - path: plugins/all
      linters:
        - revive
    - path: plugins/test
      linters:
        - revive
  # The list of ids of default excludes to include or disable. By default it's empty.
  # See the list of default excludes here https://golangci-lint.run/usage/configuration.
  include:
    - EXC0001
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0009
    - EXC0010
    - EXC0011
```
</details>

### Go environment

<details>

```console
windos-latest github runner
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here

https://github.com/alibaba/ilogtail/runs/4312542890?check_suite_focus=true
```
![image](https://user-images.githubusercontent.com/31562192/143249088-54c473b8-3dcb-4b95-bfd2-cdf0c55046f9.png)

</details>

### Code example or link to a public repository

<details>

```go
https://github.com/alibaba/ilogtail
```

</details>
