### DISCUSSION TITLE
skip-files option still reports errors from revive

### DISCUSSION THREAD

**Discussion by aniforprez** [golangci/golangci-lint#2469] [Q&A] [answered]
I've configured some files to be ignored, specifically the resolvers from gqlgen since they will always have certain issues since they're partially generated files but golangci-lint still seems to be reporting errors from those files

```yaml
run:
  skip-files:
    - "./internal/graph/*\\.resolvers\\.go"
  linters:
    enable:
      - revive
linters-settings:
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    severity: warning
    rules:
      - name: line-length-limit
        arguments: [88]
```

Lint output
```
internal/graph/account.resolvers.go:21: line-length-limit: line is 126 characters, out of limit 88 (revive)
func (r *mutationResolver) UpdateAccount(ctx context.Context, id string, input ent.UpdateAccountInput) (*ent.Account, error) {
```
