### DISCUSSION TITLE
`source` does not recognize specific regex expressions

### DISCUSSION THREAD

**Discussion by rexagod** [golangci/golangci-lint#2775] [Q&A] [answered]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Specifying `\w` for the `issues.exclude-rules.linters[*].source` field throws error saying that it's not recognized.

### Version of golangci-lint

<details>

```console
# Installed using pacman on 5.15.25-1-MANJARO
$ golangci-lint --version
golangci-lint has version v1.45.0 built from (unknown, modsum:"h1:T2oCVkYoeckBxcNS6DTYiSXN2QcTNuAWaHyLGfqzMlU=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  concurrency: 8
  go: "1.17"
output:
  sort-results: true
  format: tab
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//.kubebuilder:.*"
    - linters:
        - gci
      source: "^Expected '\w'.*"
  fix: true
linters-settings:
  gci:
    no-inline-comments: true
    no-prefix-comments: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/rexagod/go/bin/"
GOCACHE="/home/rexagod/.cache/go-build"
GOENV="/home/rexagod/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rexagod/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rexagod/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rexagod/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rexagod/.go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build433855073=/tmp/go-build -gno-record-gcc-switches"

```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
ERRO Can't read config: can't read viper config: While parsing config: yaml: line 14: found unknown escape character 
```

</details>

### Code example or link to a public repository

<details>

[rexagod/mcg-osd-deployer](https://github.com/rexagod/mcg-osd-deployer)

</details>

**Comment by boring-cyborg** [comment]
Hey, thank you for opening your first Issue ! 🙂 If you would like to contribute we have a [guide for contributors](https://golangci-lint.run/contributing/quick-start/).

**Comment by ldez** [comment, marked as answer]
Hello,

> line 14: found unknown escape character 

the error message is right: in a string, the escape character must be escaped.


```
source: "^Expected '\\w'.*"
```

edit:

You also have a problem with your configuration: it is not `source` but `text`.

```yml
    - linters:
        - gci
      text: "Expected '\\w',.+"
```

**Reply by rexagod** [reply]
@ldez Thank you for clarifying this. However, I still have one more doubt. I might have missed this in the docs, but when is a `string` a `text` or `source`?

**Reply by ldez** [reply]
https://golangci-lint.run/usage/false-positives/#exclude-or-skip

Both `text` and `source` are string:
- `text` is related to the report message
- `source` to the code.


<details>

```yml
run:
  go: "1.17"

output:
  sort-results: true
  format: tab

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//.kubebuilder:.*"
    - linters:
        - varnamelen
      text: "variable name 'r'"
    - linters:
        - gosec
      text: "G101: "
    - linters:
        - gci
      text: "Expected '\\w', .*"
  # fix: true

linters-settings:
  lll:
    line-length: 120
  gomoddirectives:
      replace-allow-list:
        - github.com/go-logr/logr
        - github.com/hashicorp/vault
        - github.com/irifrance/gini
        - github.com/kubernetes-incubator/external-storage
        - github.com/mikefarah/yaml/v2
        - github.com/openshift/api
        - github.com/portworx/sched-ops
        - k8s.io/api
        - k8s.io/apiextensions-apiserver
        - k8s.io/apimachinery
        - k8s.io/apiserver
        - k8s.io/cli-runtime
        - k8s.io/client-go
        - k8s.io/cloud-provider
        - k8s.io/cluster-bootstrap
        - k8s.io/code-generator
        - k8s.io/component-base
        - k8s.io/component-helpers
        - k8s.io/controller-manager
        - k8s.io/cri-api
        - k8s.io/csi-translation-lib
        - k8s.io/kube-aggregator
        - k8s.io/kube-controller-manager
        - k8s.io/kube-proxy
        - k8s.io/kube-scheduler
        - k8s.io/kubectl
        - k8s.io/kubelet
        - k8s.io/legacy-cloud-providers
        - k8s.io/metrics
        - k8s.io/mount-utils
        - k8s.io/sample-apiserver
        - sigs.k8s.io/controller-runtime
#  gci:
#    no-inline-comments: true
#    no-prefix-comments: true

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
```

</details>

**Reply by rexagod** [reply]
Makes sense, thank you again. 🎉

**Comment by rexagod** [comment]
I'm trying to skip the first two cases below by specifying the `\w` in the regex string. A single apostrophe is supposed to indicate literal characters themselves.

Nonetheless, this still fails.

```console
controllers/managedmcg_controller_test.go:23:2  gci  Expected 'n', Found 'v' at controllers/managedmcg_controller_test.go[line 23,col 2]
main.go:25:14                                   gci  Expected 'g', Found 'r' at main.go[line 25,col 14]
readinessProbe/main.go:16:1                     gci  Expected '\t', Found '\n' at readinessProbe/main.go[line 16,col 1]
templates/noobaa.go:20:2                        gci  Expected '_', Found '/' at templates/noobaa.go[line 20,col 2]
tests/suite_test.go:23:2                        gci  Expected '.', Found '"' at tests/suite_test.go[line 23,col 2]
```

**Reply by ldez** [reply]
a quote `'` just means a single quote, it doesn't have a special meaning for the regular expression.

the problem is related to your configuration: it is not `source` but `text`

```yml
    - linters:
        - gci
      text: "Expected '\\w',.+"
```
 

<details>

```yml
run:
  go: "1.17"

output:
  sort-results: true
  format: tab

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//.kubebuilder:.*"
    - linters:
        - varnamelen
      text: "variable name 'r'"
    - linters:
        - gosec
      text: "G101: "
    - linters:
        - gci
      text: "Expected '\\w', .*"
  # fix: true

linters-settings:
  lll:
    line-length: 120
  gomoddirectives:
      replace-allow-list:
        - github.com/go-logr/logr
        - github.com/hashicorp/vault
        - github.com/irifrance/gini
        - github.com/kubernetes-incubator/external-storage
        - github.com/mikefarah/yaml/v2
        - github.com/openshift/api
        - github.com/portworx/sched-ops
        - k8s.io/api
        - k8s.io/apiextensions-apiserver
        - k8s.io/apimachinery
        - k8s.io/apiserver
        - k8s.io/cli-runtime
        - k8s.io/client-go
        - k8s.io/cloud-provider
        - k8s.io/cluster-bootstrap
        - k8s.io/code-generator
        - k8s.io/component-base
        - k8s.io/component-helpers
        - k8s.io/controller-manager
        - k8s.io/cri-api
        - k8s.io/csi-translation-lib
        - k8s.io/kube-aggregator
        - k8s.io/kube-controller-manager
        - k8s.io/kube-proxy
        - k8s.io/kube-scheduler
        - k8s.io/kubectl
        - k8s.io/kubelet
        - k8s.io/legacy-cloud-providers
        - k8s.io/metrics
        - k8s.io/mount-utils
        - k8s.io/sample-apiserver
        - sigs.k8s.io/controller-runtime
#  gci:
#    no-inline-comments: true
#    no-prefix-comments: true

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
```

</details>
