### DISCUSSION TITLE
Params or flags to custom private linters

### DISCUSSION THREAD

**Discussion by martinsaporiti** [golangci/golangci-lint#3127] [Q&A]
Hi everyone, I'm coding a custom private linter for my company. 
I want to ask if there is a way to run a custom linter sending parameters.
I mean, something like this:

```yaml
custom:
  importsorder:
    path: ./goimportsorder.so -pattern="a pattern"
    description: The description of the linter
    original-url:  the url
```

Thanks in advance!
