### DISCUSSION TITLE
How to specify github repo as path in custom linter?

### DISCUSSION THREAD

**Discussion by BuilderHarrison** [golangci/golangci-lint#3222] [Q&A]
Hey folks,
I was wondering if we are able to specify a repo to pull the .so file from when specifying a custom linter, instead of having to have this file locally? Or if there is another way you have overcome this, so there is a central place to manage your custom linters, please suggest away! 

Cheers,
 Harrison

```
linters-settings:
  custom:
    custom_linter:
      path: custom_linters.so
      description: Internal custom linters
      
```
