### DISCUSSION TITLE
revive add constant not works after update

### DISCUSSION THREAD

**Discussion by hamedprog** [golangci/golangci-lint#3286] [Q&A] [answered]
after updating to the latest version of golangci-lint, revive config is not applied and linter throws errors for add constant for all ints and strings. this is my revive config:

```
revive:
    confidence: 1
    enable-all-rules: true
    ignore-generated-header: true
    max-open-files: 2048
    rules:
      - arguments:
          - allowFloats: '0.0,2178.91,179.91'
            allowInts: '0o600,0,2,1,5,10,16,76,1'
            allowStrs: '"","0","aaf4e330948c27b9"'
            maxLitCount: '10'
        disabled: false
        name: add-constant
        severity: error
      - arguments:
          - 4
        disabled: true
        name: argument-limit
        severity: error
    severity: error
```
