### DISCUSSION TITLE
best practice for interface assertion?

### DISCUSSION THREAD

**Discussion by seaguest** [golangci/golangci-lint#3662] [Q&A] [answered]
Hello,

The following code pass golangci-lint 1.48.0, but failed in 1.51.2
```
var _ error = (*ValidationError)(nil)

Error return value is not checked (errcheck)

```
so what is the encouraged way to check if a struct implement the interface?

thanks in advance!

**Comment by ldez** [comment]
Hello,

golangci-lint is a wrapper around linters, so the rules are related to linter like [errcheck](https://github.com/kisielk/errcheck) not to golangci-lint itself.

In all cases, I'm not able to reproduce your problem, so I think you have another problem.

<details>

```go
package main

import (
	"errors"
)

var _ error = (*ValidationError)(nil)

type ValidationError struct {
	Msg string
}

func (v *ValidationError) Error() string {
	return v.Msg
}

func main() {
	foo("huu")
}

func foo(a string) error {
	if a == "a" {
		return errors.New("OOPS")
	}

	return nil
}
```

```console
$ golangci-lint version       
golangci-lint has version 1.51.2 built from 3e8facb4 on 2023-02-19T21:43:54Z
$ golangci-lint run -Eerrcheck
foo.go:18:5: Error return value is not checked (errcheck)
        foo("huu")
           ^
```

</details>

**Comment by seaguest** [comment, marked as answer]
```console

seaguest@DEV:~/Work/monitor/test$ golangci-lint version
golangci-lint has version 1.51.2 built from 3e8facb4 on 2023-02-19T21:43:54Z
seaguest@DEV:~/Work/monitor/test$ 
seaguest@DEV:~/Work/monitor/test$ 
seaguest@DEV:~/Work/monitor/test$ cat t4.go
package main

import (
    "errors"
)

var _ error = (*ValidationError)(nil)

type ValidationError struct {
    Msg string
}

func (v *ValidationError) Error() string {
    return v.Msg
}

func main() {
    foo("huu")
}

func foo(a string) error {
    if a == "a" {
        return errors.New("OOPS")
    }

    return nil
}
seaguest@DEV:~/Work/monitor/test$ golangci-lint run -Eerrcheck 
t4.go:7:5: Error return value is not checked (errcheck)
var _ error = (*ValidationError)(nil)
    ^
t4.go:18:5: Error return value is not checked (errcheck)
    foo("huu")
       ^
```

**Reply by ldez** [reply]
What is your configuration?

**Reply by seaguest** [reply]
I think the default configuration is used when I run directly in command line?

Here is previous ci lint yml

```
name: Golang Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      'go/**'
  pull_request:
    paths:
      'go/**'
jobs:
  golangci:
    strategy:
      matrix:
        go: ['>=1.18.0']
        os: [ubuntu-20.04]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.48.0
          # Optional: working directory, useful for monorepos
          working-directory: go
          # increasing timeout to 3m, looks like others have reported this issue as well
          # https://github.com/golangci/golangci-lint-action/issues/297
          args: "--config=.golangci.yml --timeout=4m"

```

**Reply by ldez** [reply]
> I think the default configuration is used when I run directly in command line?

errcheck is not enabled by default and you have ` args: "--config=.golangci.yml`.

I'm sure you have this kind of configuration:

```yml
linters-settings:
  errcheck:
    check-blank: true
```

https://github.com/golangci/golangci-lint/pull/3482
https://github.com/kisielk/errcheck/pull/219

So I recommend opening an issue on the [errcheck repository](https://github.com/kisielk/errcheck).

**Reply by seaguest** [reply]
yes, we do, please see my following `./go/.golangci.yml`


./go/.golangci.yml

```yml
---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  timeout: 180s
  skip-dirs:
issues:
  exclude-rules:
    - path: _test\.go
      linters:
      - dupl
      - goconst
linters:
  enable:
    - revive
    # - gosec, disable for now, needs to tweak parameters 
    - unconvert
    - gocyclo
    - goconst
    - goimports
    - gocritic
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    # report about shadowed variables
    check-shadowing: true
    enable:
      - atomicalign
  gocyclo:
    min-complexity: 50
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true

```
