### DISCUSSION TITLE
Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"

### DISCUSSION THREAD

**Discussion by 0xfaceDEFI** [golangci/golangci-lint#3752] [Q&A]
```
Run golangci/golangci-lint-action@v3
prepare environment
run golangci-lint
  Running [/home/runner/golangci-lint-1.29.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
  
  Error: golangci-lint exit with code 4
  Ran golangci-lint in 60125ms
```

```
name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          timeout: 10m
          working-directory: .
          args: --issues-exit-code=0


```
