### DISCUSSION TITLE
How do I disable paralleltest for subtests?

### DISCUSSION THREAD

**Discussion by MichaelSnowden** [golangci/golangci-lint#3839] [Q&A] [answered]
I just want paralleltest to check top-level test functions for missing calls to `t.Parallel()`. There's a lot of code at my company which has non-parallelizable subtests, and only some of it is table-driven tests. Is there a way to do this?

**Comment by Antonboom** [comment, marked as answer]
https://golangci-lint.run/usage/linters/#paralleltest

```yml
linters-settings:
  paralleltest:
    ignore-missing-subtests: false
```
