### DISCUSSION TITLE
Go doc enforcement

### DISCUSSION THREAD

**Discussion by chrishalbert** [golangci/golangci-lint#4323] [Q&A] [answered]
I'd like to keep my code well documented so I was looking for a [go doc comment](https://go.dev/doc/comment) enforcement linter. Am I totally missing the obvious? I feel like I am. Thanks

**Comment by bombsimon** [comment, marked as answer]
Have a look at [exclude-use-defaults](https://golangci-lint.run/usage/configuration/#command-line-options) and [default exclusions](https://golangci-lint.run/usage/false-positives/#default-exclusions). By default no matter what linters you enable some issues are always excluded for historical reasons. One if them is EXC0002 from `golint`, one is EXC0011 from `stylecheck` and two others are EXC0013 and EXC0014 from `revive`.

Try passing `--enable revive --exclude-use-defaults=false` or setting this config and you should see reports.

```yaml
issues:
  exclude-use-defaults: false

  # Or include them, not 100% sure this works
  include:
    - EXC0013
    - EXC0014

linters:
  enable:
    - revive
```
