### DISCUSSION TITLE
Error on add a custom plugin in golangci-lint

### DISCUSSION THREAD

**Discussion by hobbitx** [golangci/golangci-lint#4345] [Q&A] [answered]
Good evening, 

I'm trying to create a custom linter for my application.

But I can't add them to `golangci-lint`. 

I  build my linter using command:
` CGO_ENABLED=1 go build -buildmode=plugin plugin/main.go `

added in `.golangci.yml
`
``` yaml
  custom:
    example:
      path: /Users/username/dev/go-lint/pkg/golinters/main.so
      description: The description of the linter
      original-url: github.com/REDACTED/go-lint
``` 

and build ` golangci-lint` using:
`CGO_ENABLED=1 make build `

I also tried to compile just the [example plugin](https://github.com/golangci/example-plugin-linter), and it also shows the same error:

```
ERRO Unable to load custom analyzer example:/Users/username/dev/go-lint/pkg/golinters/main.so, plugin.Open("/Users/username/dev/go-lint/pkg/golinters/main"): plugin was built with a different version of package internal/goarch 
```
