### DISCUSSION TITLE
gosec rule not getting ignored

### DISCUSSION THREAD

**Discussion by abhinav-bhushan** [golangci/golangci-lint#4413] [Q&A] [answered]
I am not able to ignore G112 and some other errors for my code

This is my golangci.yaml-
```
run:
  modules-download-mode: readonly
linter-settings:
  gosec:
     excludes:
      - G108 # Profiling endpoint automatically exposed on /debug/pprof
      - G112 # Potential slowloris attack

linters:
  disable-all: true
  enable:
    - gosec
issues:
  exclude-use-default: false
  max-same-issues: 0
```
It's still showing me G112 for my code.How to exclude it ?

```
abbhushan@GWP14DMG6T blog-go % golangci-lint run | grep G112
main.go:55:16: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
main.go:59:19: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
```
