### DISCUSSION TITLE
Best way to enable certain linters for tests separately?

### DISCUSSION THREAD

**Discussion by rexagod** [golangci/golangci-lint#4789] [Q&A]
Hello. 👋🏼 

I have a `golangci.yml` file that includes the following content (trimmed for the sake of brevity).

```yaml
run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - test
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - ...
```

This, as you can see, skips over all tests, and is essentially intended to lint only the non-test areas of the codebase, which is does perfectly fine.

However, I want to have a set of linters for tests as well. Below are two approaches I've considered.

- A separate `golangci.test.yml` file dedicated to tests.
- Using the [`issues:`](https://golangci-lint.run/usage/configuration/#issues-configuration) section within the same `golangci.yml` (as below).

```yaml
...
tests: true
skip-dirs:
  - vendor
...

linters: # (A)
...

issues:
  exclude-rules:
    - path: _test\.go
      linters: (B)
       - ... # NOTE: This is an inverted list of (A) and a subset of it. An empty list here means enabling all linters in (A) for tests. Similarly, a list same as (A) here implies not enabling any linter for tests.
```

What is the best practice for this use-case?
