### DISCUSSION TITLE
How to set the severity for custom linters.

### DISCUSSION THREAD

**Discussion by kitimark** [golangci/golangci-lint#4917] [Q&A] [answered]
Hello, community.

I want to set the severity into the nilaway lint plugin for print error with info message and make it not return an error but the severity is not forcing to info message

Because I'm working on a large project that contained a lot of nil potential errors, I want to force it into an info message to encourage my colleague to fix this. I don't want to break my CI it will block my development processes. 

Does anyone know how it is configured?

examples:

custom-gcl.yml
```yml
version: v1.57.2
name: golangci-lint
destination: bin

plugins:
  - module: go.uber.org/nilaway
    import: go.uber.org/nilaway/cmd/gclplugin
    version: latest
```
.golangci.yml
```yml
linters:
  enable:
    - nilaway
linters-settings:
  custom:
    nilaway:
      type: module
      description: Static analysis tool to detect potential nil panics in Go code.
      settings:
        # Settings must be a "map from string to string" to mimic command line flags: the keys are
        # flag names and the values are the values to the particular flags.
        include-pkgs: some-package.com/my-package
severity:
  default-severity: error
  rules:
    - linters:
        - nilaway
      severity: info
```
