### DISCUSSION TITLE
Using `importas` linter to require no alias to be provided for certain packages

### DISCUSSION THREAD

**Discussion by denisvmedia** [golangci/golangci-lint#5221] [Q&A] [answered]
I used this configuration to guarantee `errors` package having no alias:

```
      - pkg: errors
        alias: ""
```

Now, I discovered that some colleagues are adding an alias to the `someinternalpkg/log` package (which is not desired). I decided to expand the configuration:

```
      - pkg: errors
        alias: ""
      - pkg: someinternalpkg/log
        alias: ""
```

But it leads to the following problem:

```
ERRO [linters_context] invalid configuration, multiple packages with the same alias: alias= packages=[someinternalpkg/log,errors]
```

Is it possible to achieve this using `importas` (or alternatively any other linter)?

To me not giving an alias should not be considered as a duplicate alias.

**Comment by ldez** [comment]
Hello,

I think you can use:

```yml
linters-settings:
  importas:
    # Do not allow non-required aliases.
    # Default: false
    no-extra-aliases: true
```

https://golangci-lint.run/usage/linters/#importas

```console
$ golangci-lint run
importas.go:3:8: import "fmt" has alias "koo" which is not part of config (importas)
import koo "fmt"
       ^
```

**Comment by denisvmedia** [comment]
But then it would force all packages not mentioned in config to not have aliases, which would not work for our huge and old project.

Note, we also have `no-unaliased: true`.

**Reply by ldez** [reply]
:thinking: I will see what I can do.

**Reply by denisvmedia** [reply]
I can try to provide a PR, if you think this is something we can allow in the linter.

**Reply by ldez** [reply]
I have a fix

**Reply by ldez** [reply, marked as answer]
https://github.com/golangci/golangci-lint/pull/5222

**Comment by ccoVeille** [comment]
I'm discovering the feature you mentioned it's very interesting

```yaml
      - pkg: errors
        alias: ""
      - pkg: someinternalpkg/log
        alias: ""
```

I checked and this was possible without the 

- https://github.com/golangci/golangci-lint/pull/5222

```yaml
      - pkg: errors|someinternalpkg/log
        alias: ""
```

This was also possible

```yaml
      - pkg: errors
        alias: "errors"
      - pkg: someinternalpkg/log
        alias: "log"
```

But, I do prefer the solution @ldez provided
