### DISCUSSION TITLE
go fmt not working as expected in golangci-lint

### DISCUSSION THREAD

**Discussion by singh1203** [golangci/golangci-lint#5378] [Q&A] [answered]
I am using pre-commit-config.ymal file for linting the whole repository; more specifically, I am expecting to get `go fmt` linting whenever I am executing `golangci-lint run ./...` but instead it passes the run but no linting takes place whereas I am manually trying to execute (for example): `go fmt -s` it works properly, and also  I have confirmed that `.golangci.yaml  ` is not being overridden by any other `.golangci.yaml` in the directory 

<details><summary>pre-commit-config.yml</summary>

```yml
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.63.4
    hooks:
      # no built-in support for multiple go.mod
      # https://github.com/golangci/golangci-lint/issues/828
      - id: golangci-lint-full
        name: golangci-lint-full-a
        entry: bash -c 'cd a && golangci-lint run --timeout=5m --enable=gofmt'
      - id: golangci-lint-full
        name: golangci-lint-full-parquet
        entry: bash -c 'cd p && golangci-lint run'
      - id: golangci-lint-full
        name: golangci-lint-full-internal
        entry: bash -c 'cd internal && golangci-lint run'
  
# - repo: local
#   hooks:
#     - id: go-fmt
#       name: go fmt
#       language: system
#       entry: bash -c "go get golang.org/x/tools/cmd/goimports@latest && go fmt ./..."
#       pass_filenames: false

```

</details>

<details><summary>.golangci.yaml</summary>

```yml
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gofmt
    - goimports
    - staticcheck
issues:
  fix: true

```

</details>
