### DISCUSSION TITLE
Warn about unused linter settings

### DISCUSSION THREAD

**Discussion by alexandear** [golangci/golangci-lint#5644] [General] [answered]
I propose that Golangci-lint should raise a warning when it detects an unused linter settings.

Consider the following configuration:
```yaml
version: "2"
linters:
  default: none
  enable:
    # - rowserrcheck
    - whitespace
  settings:
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
```

When running golangci-lint, it should print something like:

```
$ golangci-lint run
WARN The configuration setting for `rowserrcheck` is unused. Consider removing `linters.settings.rowserrcheck`.
```
