### DISCUSSION TITLE
goimports differ between  golangci-lint fmt  and  goimports -l -w .

### DISCUSSION THREAD

**Discussion by yanjinbin** [golangci/golangci-lint#5684] [Q&A] [answered]
env:
`go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2`
golangci-lint has version v2.0.2 built with go1.23.8 `

`https://pkg.go.dev/golang.org/x/tools/cmd/goimports` version is latest with Version: v0.31.0

cmd: ` goimports -l -w .` or ` golangci-lint fmt  --enable goimports`

output:

```go
package main

import (
	"context"
	"errors"
	"fmt"
	
	"dental/api/web/src/router"

	"github.com/gin-gonic/gin"      ###   differ here
	"github.com/gookit/color"
)
```

cmd: `golangci-lint fmt .` 

output
```go
package main

import (
	"context"
	"errors"
	"fmt"
	
	"dental/api/web/src/router"
	"github.com/gin-gonic/gin"
	"github.com/gookit/color"
)
```
my .golangci.yaml will be like
```yaml

version: "2"
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: fast

  settings:
    nestif:
      min-complexity: 10
    cyclop:
      max-complexity: 15
    tagliatelle:
      case:
        rules:
          json: snake
          toml: snake
          form: snake
          mapstructure: snake
          xml: snake
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
```

i do not know why this will happen  
i like the output of ` goimports -l -w .`

**Comment by ldez** [comment]
can you provide a reproducible example?

**Comment by ldez** [comment, marked as answer]
You are using 4 formatters at the same time.

To have the same format as `goimports`, you must enable only `goimports`.

**Reply by yanjinbin** [reply]
step 1
```
 golangci-lint run --fix  api/admin/... api/boilerplate/...  api/pkg/...     gen/..
. playground/... -c .golangci.yaml
```

step 2:
```
goimports -l -w .
```

the output diff as you see here:

<details>
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/fd1b6bb6-8dba-42c7-921d-1304ffe8a5ee" />
</details>

golangci-lint version :  golangci-lint has version 2.0.2 built with go1.24.1 from 2b224c2 on 2025-03-25T20:33:26Z

```
go install golang.org/x/tools/cmd/goimports@latest
```

<details>
<summary>.golangci.yaml</summary>

```yaml 
version: "2"
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: fast
  enable:
    - bodyclose
    - canonicalheader
    - contextcheck
    - funlen
    - nestif
    - cyclop
    - tagliatelle
    - tagalign
    - err113
    - errorlint
    - nilnil
    - nlreturn
    - noctx
    - prealloc
    - rowserrcheck
    - whitespace
    - wsl
  disable:
    - wsl
    - gomodguard
    - mnd
    - gocyclo
#    - lll
    - depguard
    - testpackage

  settings:
    funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
      lines: 120
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
      statements: 80
    nestif:
      min-complexity: 10
    cyclop:
      max-complexity: 15
    tagliatelle:
      case:
        rules:
          json: snake
          form: snake
          mapstructure: snake
          xml: snake
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
```


</details>
