### DISCUSSION TITLE
multiple linters missed issues in scanning

### DISCUSSION THREAD

**Discussion by ParlamLiao** [golangci/golangci-lint#5702] [Q&A]
**Overview of the Situation**
A large-scale project is being integrated with golangci-lint, starting with scanning the entire project to understand the current issues. Under consistent versions of Go, golangci-lint, and the configuration file golangci-lint.yml, there are some pre-existing issues that were not detected in earlier scans. These issues only started to be detected after the project went through several iterations unrelated to the original issues.

**Go Version**
1.20

**golangci-lint Versions**
v1.51.0
v1.53.3
v1.55.2

**Installation Method**
```
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin <golangci-lint version>
```

**Linters currently observed to have missed issues**
gosec / gocognit / errname

<details>
<summary>example 1</summary>

<img width="989" alt="image" src="https://github.com/user-attachments/assets/5d333eee-e906-427b-9a0e-2d871ccc9a07" />

</details> 

<details>
<summary>example 2</summary>

<img width="788" alt="image" src="https://github.com/user-attachments/assets/d2efa8e6-b367-47df-a144-ad1d945b5416" />

</details> 

<details>
<summary>example 3</summary>

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/bb45e066-2a3e-4872-940c-32774d728312" />

</details>

**Comment by ldez** [comment]
Without your configuration, it's not possible to understand the context.

Note: you are using very old versions of Go and golangci-lint (3 years)

**Reply by ParlamLiao** [reply]
Our project now using old go version. and it's difficult to upgrade go version (for lots of dependencies)
As a result, we can not use newer version of golangci-lint.

Here is the config setting. All scans use the this same config.

<details>

```yml
linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019'  # github.com/golang/protobuf/proto is allowed only by msg.TypeMsgCodec.Marshal/ExtractEndpoint
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
    packages-with-error-message:
      - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  gocognit:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 18
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 120
    statements: 50
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  gosec:
    excludes:
      - G404

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    - asasalint
    - asciicheck
    - bidichk
    #    - contextcheck
    - depguard
    - dogsled
    - dupl
    - dupword  
    - durationcheck
    - errchkjson
    - errname
    - execinquery
    #    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    #    - ireturn
    - loggercheck  
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - predeclared
    - reassign   
    #    - sqlclosecheck
    - stylecheck
    #    - tagliatelle
    - tenv
    - typecheck
    - unconvert
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

run:
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test\\.go$"
  # Allow multiple parallel golangci-lint instances running.
  # If false, golangci-lint acquires file lock on start.
  # Default: false
  allow-parallel-runners: true

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.51.2 # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
```

</details>
