### DISCUSSION TITLE
`golangci-lint run` fails on Windows when a formatter is enabled

### DISCUSSION THREAD

**Discussion by alexandear** [golangci/golangci-lint#5840] [Q&A]
Got [the following error](https://github.com/alexandear-org/golangci-lint-eol-windows/actions/runs/15303464336/job/43049954086#step:4:35) when running `golangci-lint` on `windows-latest` in GitHub Actions:
```console
Running [D:\a\_temp\78415d87-82ae-47b8-8dd1-8d7e900d18f1\golangci-lint-2.1.6-windows-amd64\golangci-lint config path] in [D:\a\golangci-lint-eol-windows\golangci-lint-eol-windows] ...
  Running [D:\a\_temp\78415d87-82ae-47b8-8dd1-8d7e900d18f1\golangci-lint-2.1.6-windows-amd64\golangci-lint config verify] in [D:\a\golangci-lint-eol-windows\golangci-lint-eol-windows] ...
  Running [D:\a\_temp\78415d87-82ae-47b8-8dd1-8d7e900d18f1\golangci-lint-2.1.6-windows-amd64\golangci-lint run  --verbose] in [D:\a\golangci-lint-eol-windows\golangci-lint-eol-windows] ...
  Error: main.go:1:1: File is not properly formatted (gofmt)
  package main
  ^
  1 issues:
  * gofmt: 1
```

On `ubuntu-latest`, everything [works fine](https://github.com/alexandear-org/golangci-lint-eol-windows/actions/runs/15303464336/job/43049954088).

Example: https://github.com/alexandear-org/golangci-lint-eol-windows

<details><summary>Setup</summary>
<p>

`.golangci.yaml`:

```yaml
version: "2"

linters:
  default: none
formatters:
  enable:
    - gofmt
```

Workflow:
```yaml
name: PR

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-go:
    name: "Lint Go"
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    - uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: --verbose
```

`main.go`:

```go
package main

func main() {}
```

`go.mod`:

```
module github.com/alexandear-org/golangci-lint-eol-windows

go 1.23
```

</p>
</details> 

However, when I added [the following step](https://github.com/alexandear-org/golangci-lint-eol-windows/pull/1) before the `checkout` step in the workflow, [the issue disappeared](https://github.com/alexandear-org/golangci-lint-eol-windows/pull/1/checks#step:5:35):

```yaml
    - name: Force git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
```

Found this issue while integrating `golangci-lint` in lima-vm/lima#3586.

Not sure if this is a bug, so I’ve created a discussion instead of an issue.
