### ISSUE TITLE
Make and promote recommended presets like in eslint, tslint

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#1141]
## Motivation
1. Some linters are duplicated partially or fully: [errcheck, goerr13, staticcheck], [modguard, depguard], [golint, stylecheck]
2. Some really cool linters aren't used because there are too many linters and only some of them are enabled by default.
3. Configuration became too large. Even maintainers don't know all configuration options and linters.

## Proposal
We need to research how eslint, tslint, etc work with that. My first guess is to introduce presets like `golangci:recommended` and add ability to share and reuse such presets like [airbnb-eslint](https://www.npmjs.com/package/eslint-config-airbnb).

**Comment by thepwagner** [comment]
https://github.com/golangci/golangci-lint/issues/2137 is perhaps related, especially when this idea gets into shared presets like `airbnb-eslint`.

**Comment by ringerc** [comment]
I quickly hit issues with trying to promote a preferred default set of `golangci-lint` rules for my org, while preserving individual teams' ability to customise, add to and override them on a per-component / per-repo basis. Short of hacks in build automation like pre-processing a `.golangci.yaml.d` snippets directory to generate a config as part of build automation I didn't find a sensible way to do it.

The lightest-way to satisfy this might be to support a config-directory in `golangci-lint` like a `.golangci.yaml.d`. If the configuration points to a directory, all files in that directory are read in locale "C" sort-order and merged. How well this would work will depend a bit on how the config is expressed though; to be useful it has to be possible to match and delete array entries created by earlier configs.

**Comment by ldez** [comment]
Just to link the discussion topic: https://github.com/golangci/golangci-lint/discussions/3954

**Comment by chaindead** [comment]
### There is my proposal for problem

What I actually want is boring: inherit a *versioned* base config and adjust it locally, without copy-paste drift and without the MVS surprise.

Borrow the model GitLab CI already proved at scale: an `include` that names one or more base configs, with your local file deep-merged on top. No new subcommand and no separate step - `golangci-lint run` keeps working as-is, so editors and CI don't need to know anything changed.

```yaml
version: "2"

include:
  # A versioned base from another repo. `ref` is pinned explicitly, so no MVS.
  - project: github.com/acme/go-linter
    ref: v1.4.0
    file: .golangci.base.yml
  # ...or a plain URL (CI / public bases).
  - remote: https://raw.githubusercontent.com/acme/go-linter/v1.4.0/.golangci.base.yml
  # ...or a fragment that lives in this repo.
  - local: configs/.golangci.team.yml

# Everything below is merged on top of the included layers - your file wins last.
linters:
  enable: [sqlclosecheck]
  disable: [wsl]
  settings:
    gocyclo:
      min-complexity: 20
```

#### Syntax

`include` is a list. Each entry is a single source in one of three shapes:

- `project` - a repository to fetch the base from. `ref` pins a tag or commit (this is what removes the MVS problem), and `file` is the path inside that repo (defaults to `.golangci.yml`).
- `remote` - a direct URL to a config file.
- `local` - a path on disk, resolved relative to the file that declares the `include`, not the working directory.

Layers are applied in listed order, then your own file is applied last. Precedence is therefore simple and deterministic: later wins.

#### One level deep, on purpose

A file referenced by `include` **may not contain its own `include`**. One level, full stop - if an included file declares `include`, we error out loudly instead of silently flattening or recursing.

This is a deliberate optimization, not a missing feature, and it buys a lot:

- No cycle detection and no depth limit to design, document, or get wrong - cycles are impossible by construction.
- Caching is trivial: a base is one flat file keyed by its `ref`/URL, not a tree that has to be walked and revalidated.
- Performance is predictable: you fetch at most *N* flat files, never an unbounded graph.
- The mental model stays dead simple - "my config, plus the bases it names." If a base genuinely needs to compose other fragments, that's a signal the base itself should be flattened at its source.

In other words, capping nesting at 1 turns a whole class of hard problems into non-problems, and I haven't yet hit a real-world case that needs more than one level.

#### Merge rules

The base is **RFC 7386 (JSON Merge Patch)**: objects are deep-merged, a `null` value deletes a key, and scalars are last-wins. That handles `run.*` and `linters.settings.*` cleanly with no surprises.

Arrays are where 7386 on its own isn't enough - by spec it replaces them wholesale, and arrays are *everywhere* in this config: `enable`/`disable`, `exclusions.rules`, `run.build-tags`, and a long tail inside per-linter settings (`depguard` deny lists, `gocritic.enabled-checks`, `revive.rules`, `gosec.includes`/`excludes`, and so on). Replacing those wholesale brings the copy-paste drift right back.

So there's exactly one deliberate deviation from strict 7386: **arrays append by default** (with de-duplication for scalar lists), and a **`!replace`** marker overrides that when you want to wipe an inherited list and start fresh.

Two consequences worth stating plainly:

- For `enable`/`disable` this is already complete: append plus the existing "disable wins over enable" rule lets a repo *subtract* an inherited linter without touching the base.
- For every other list, removing a single inherited element isn't directly expressible - you `!replace` and restate the list you want. That's a real limitation of the model, and I'd rather name it than paper over it.

A short implementation note, since it usually comes up: this needs no custom YAML parser. `gopkg.in/yaml.v3` already surfaces `!replace` as a tag on the node, so the merge runs over the generic `yaml.Node` tree (scalar → last-wins, `!!null` → delete key, sequence with the `!replace` tag → replace, otherwise append+dedup, mapping → recurse) and the result is decoded into the existing config structs. The config structs don't change at all.

#### Examples

Base used below:

```yaml
# .golangci.base.yml
version: "2"
run:
  timeout: 5m
linters:
  enable: [errcheck, govet, staticcheck, unused]
  disable: [wsl]
  settings:
    gocyclo:
      min-complexity: 30
    gocritic:
      enabled-checks: [rangeValCopy, hugeParam]
  exclusions:
    rules:
      - path: _test\.go
        linters: [errcheck]
```

Override a nested scalar without disturbing its siblings:

```yaml
linters:
  settings:
    gocyclo:
      min-complexity: 20      # 30 -> 20; gocritic and everything else untouched
```

Extend lists (append is the default):

```yaml
linters:
  enable: [bodyclose]                       # -> errcheck, govet, staticcheck, unused, bodyclose
  settings:
    gocritic:
      enabled-checks: [paramTypeCombine]    # -> rangeValCopy, hugeParam, paramTypeCombine
  exclusions:
    rules:                                  # appended as a third rule
      - path: internal/gen/
        linters: [revive]
```

Drop an inherited linter (subtraction via `disable`):

```yaml
linters:
  disable: [wsl]              # wsl came from the base enable set; now it's off
```

Wipe and redefine an inherited list:

```yaml
linters:
  settings:
    gocritic:
      enabled-checks: !replace [ifElseChain]   # exactly this, base checks dropped
```

Remove a key entirely:

```yaml
run:
  timeout: null               # back to the default
```

### Open questions

These are the parts I'd want maintainer input on before any PR:

- Scope of the first cut
- Order-sensitive arrays
- Auth for private sources.
- Caching for local run
- Targeted array elem removal - not supported via my method, is it ok?


### Describe alternatives you've considered

- **Strict RFC 7386 with no array deviation** - predictable, but replacing `exclusions.rules` and every settings list wholesale defeats the purpose; unusable as the only behavior.
- **RFC 6902 (JSON Patch)** - precise element-level array ops and an `op: test` guard against drift, but array addressing is by index, so a base reordering quietly breaks override paths, and JSON Pointer reads as a foreign body inside YAML. Good as an optional escape hatch, wrong as the default model.
- **Strategic merge patch (Kubernetes-style, merge arrays by key)** - solves the array problem elegantly, but it's non-standard and needs a declared merge key per list, which `exclusions.rules` doesn't currently have.
- **A `.golangci.yml.d/` directory merged in sort order** - only addresses local fragmentation, not remote sourcing or versioning.
- **Repeated `--config a.yml --config b.yml`** - same merge engine, but it lives on the command line and doesn't fix editor behavior.
- **Status quo (Go module / `curl`)** - described above; its failure modes are the reason this proposal exists.

### Additional context

This builds directly on discussion #3954 and the issues linked at the top. I'd rather settle the merge semantics and the source-kind scope here first, and only open a PR once there's agreement on the design - I'm happy to prototype the `yaml.Node`-level merge if a working reference would help move the discussion along.
