### ISSUE TITLE
Add configuration for gochecknoglobals to not check the tests

### ISSUE THREAD

**Issue by regniblod** [golangci/golangci-lint#1153]
**Is your feature request related to a problem? Please describe.**
`gochecknoglobals` is checking the tests. 
In [gochecknoglobals README](https://github.com/leighmcculloch/gochecknoglobals) there's a description of an option to enable checking the tests, but I cannot configure whether I want the flag or not when using golang-ci

**Describe the solution you'd like**
Make the flag configurable in `.golangci.yml`

**Additional context**
I searched in the sample config and in the source code and I couldn't see a configuration option for `gochecknoglobals`. If it's already implemented and I couldn't see it please close this issue.

**Comment by ernado** [comment]
Hey, this can be achieved via `exclude-rules` :slightly_smiling_face: 

```yaml
issues:
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters: [gochecknoglobals]
```
