### ISSUE TITLE
Debug why a private linter was not added to the list

### ISSUE THREAD

**Issue by alexisvisco** [golangci/golangci-lint#1276]
Hi, I am using a private linter but it doesn't appear in the list of linters.

- I have checked the dependencies list to make sure all versions are the same as the golang ci 1.29 (http://github.com/alexisvisco/logwercase).
- My .golang-ci.yml is like that:

```yml
linters:
 enable:
   - unparam
   - misspell
   - godox
   - gocritic
   - scopelint
   - golint
   - unconvert
   - gofmt
   - exportloopref
   - govet
   - bodyclose
   - gosimple
   - goconst
   - gosec
   - logwercase

linters-settings:
  custom:
    logwercase:
      path: /home/aviscogl/go/bin/logwercase.so
      description: Analyze case of log message and WithField keys
      original-url: github.com/alexisvisco/logwercase
```

There is an option to known why a private linter is not added? https://golangci-lint.run/contributing/debug/ Does not help me ...
