### ISSUE TITLE
Failing in GitHub Actions when project contains private repositories in go.mod

### ISSUE THREAD

**Issue by Hellseher** [golangci/golangci-lint#1362]
Thank you for creating the issue!

- [ + ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [ + ] Yes, I've searched similar issues on GitHub and didn't find any.
- [ + ] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```yaml
# ...
    runs-on: "ubuntu-18.04"
# ...
      - name: "[lint|set-up] golang dependencies"
        id: "lint-golang"
        run: |
          wget https://github.com/golangci/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-amd64.deb
          sudo dpkg -i golangci-lint-1.31.0-linux-amd64.deb
          git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: "[lint] non destructive check"
        id: "ci-lint"
        run: |
          golangci-lint run --verbose
        env:
          GOPRIVATE: "github.com/<edited>/*"
# ...
```

</details>

<details><summary>Config file</summary>

```console
N/A
```

</details>

<details><summary>Go environment</summary>

```console
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/runner/.cache/go-build"
GOENV="/home/runner/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/<edited>/*"
GONOSUMDB="github.com/<edited>/*"
GOOS="linux"
GOPATH="/home/runner/go"
GOPRIVATE="github.com/<edited>/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/hostedtoolcache/go/1.13.15/x64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/hostedtoolcache/go/1.13.15/x64/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/runner/work/<edited>/<edited>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build380172567=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```console
golangci-lint run --verbose;
go: github.com/<edited> invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/runner/go/pkg/mod/cache/vcs/<edited>: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/<edited>' not found
level=info msg="[config_reader] Config search paths: [./ /home/runner/work/<edited>/<edited> /home/runner/work/<edited> /home/runner/work /home/runner /home /]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (name|exports_file|deps|files|imports|types_sizes|compiled_files) took 448.16677ms"
level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: github.com/<edited>: invalid version: git fetch -f https://github.com/<edited> refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/runner/go/pkg/mod/cache/vcs/<edited>: exit status 128:\n\tremote: Repository not found.\n\tfatal: repository 'https://github.com/<edited>/' not found\n"
level=info msg="Memory: 6 samples, avg is 70.8MB, max is 70.8MB"
level=info msg="Execution took 454.295361ms"GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build380172567=/tmp/go-build -gno-record-gcc-switches"
```

</details>
