### ISSUE TITLE
github action log output doesn't print the affected file name & line

### ISSUE THREAD

**Issue by dprotaso** [golangci/golangci-lint#1461]
Please include the following information:

<details><summary>Version of golangci-lint</summary>

```yaml
      - id: golangci_configuration
        uses: andstor/file-existence-action@v1
        with:
          files: .golangci.yaml
      - name: Go Lint
        if: steps.golangci_configuration.outputs.files_exists == 'true'
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
```

</details>

<details><summary>Config file</summary>

```yaml
run:
  timeout: 5m

  build-tags:
    - e2e

  skip-dirs:
    - pkg/client

linters:
  enable:
    - asciicheck
    - golint
    - gosec
    - prealloc
    - stylecheck
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
1.15
```

</details>

<details><summary>Verbose output of running</summary>

https://github.com/knative/networking/pull/233/checks?check_run_id=1275974348

</details>

I had to view the 'files changed' page to see the lints
