### ISSUE TITLE
Make private linters support parameters

### ISSUE THREAD

**Issue by chenlujjj** [golangci/golangci-lint#1512]
**Is your feature request related to a problem? Please describe.**
I'm working on a custom private linter which checks that if `main.go` has some specific imports from our company's code base. It would be nice if I can config the imports names in settings like other public linters. Now I have to hard code.

**Describe the solution you'd like**
The config file may look like this (part of it):
```
linters:
  enable:
    - gocheckimports

linters-settings:
 custom:
  gocheckimports:
   path: ./gocheckimports.so
   description: check imports
   settings:
     key1: value1
     key2: value2
```
