### ISSUE TITLE
False positive "should have a package comment" from golint

### ISSUE THREAD

**Issue by ernado** [golangci/golangci-lint#1556]
Having following config:
```yaml
linters-settings:
  golint:
    min-confidence: 0
issues:
  exclude-use-default: false
```

I'm getting an error for each file in package (expect one with actual documentation):
```
bin/bytes.go:1:1: should have a package comment, unless it's in another file for this package (golint)
package bin
```

Looks like `golint` is not package-aware?

Related: #456 #464

Update:
If `min-confidence: 0` is removed, those issues are not reported :thinking:
