### ISSUE TITLE
Can't disable specific revive rules after upgrading from 1.37.0 to 1.37.1

### ISSUE THREAD

**Issue by ejain** [golangci/golangci-lint#1770]
After upgrading from 1.37.0 to 1.37.1, configuring explicit rules for the revive linter in the linters-settings no longer prevents other revive rules from running. This is unfortunate, as revive doesn't output rule codes that could be used to filter on...

Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```console
$ golangci-lint --version
golangci-lint has version 1.37.1 built from b39dbcd on 2021-02-22T04:34:44Z
```

</details>

<details><summary>Config file</summary>

```yaml
linters-settings:
  revive:
    rules:
      - name: if-return
        severity: error
      - name: var-declaration
        severity: error
linters:
  disable-all: true
  enable:
    - revive
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
go version go1.15.8 darwin/amd64
```

</details>
