### ISSUE TITLE
Feature request: exit code per linter

### ISSUE THREAD

**Issue by ewgRa** [golangci/golangci-lint#193]
There is exit code config settings applied globally. And there is a case, when someone want run some linters with exit code 0 (as just recommendation), some with 1 (as critical for pull request for example).

One way to achieve it, it is run golangci-lint with different "--config" option multiple times.

Another way to introduce exit code on linter level, something like this:
```
  linters-settings:
...
    go-critic:
      - exit-code: (proxy|[0-9]+)
```
 
What do you think? I can create PR in case if this idea have support.
