### ISSUE TITLE
Feature request: run same linter multiple times with different settings

### ISSUE THREAD

**Issue by ewgRa** [golangci/golangci-lint#194]
There is possible case, when someone want to run same linter with different settings, that is impossible to what I see from current config structure.

What about idea to configure linters like this:

```
  linters-settings:
    gocritic-recommended:
        linter: go-critic
        config: config-recommended.json
    gocritic-required:
        linter: go-critic
        config: config-required.json
```
