### ISSUE TITLE
release v1.42.1 regression for `goimports` and build tags

### ISSUE THREAD

**Issue by acabarbaye** [golangci/golangci-lint#2231]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

When using latest version i.e. v1.42.1 ([alpine docker](https://hub.docker.com/layers/golangci/golangci-lint/latest-alpine/images/sha256-fa1e0fc7de1a8882417bfd4271dd1425d6a3efe4ce7c9902d26b2a011d4fb43b?context=explore)), then `goimports`  starts failing with any file using build tags
such as 
```
// +build integration

package ***

import (
.....
```
error is, as follows:
```
***.go:1: File is not `goimports`-ed with -local github.com/**** (goimports)
// +build integration
```

### Version of golangci-lint

v1.42.1 ([alpine docker](https://hub.docker.com/layers/golangci/golangci-lint/latest-alpine/images/sha256-fa1e0fc7de1a8882417bfd4271dd1425d6a3efe4ce7c9902d26b2a011d4fb43b?context=explore))

### Configuration file

defaults

### Go environment

this is using golangci-lint docker image 

### Verbose output of running

<details>

```
***.go:1: File is not `goimports`-ed with -local github.com/**** (goimports)
// +build integration
```

</details>

### Code example or link to a public repository

<details>

</details>

**Comment by ldez** [comment]
Hello,

can you provide a reproducible example?

With the [default configuration](https://golangci-lint.run/usage/linters/#enabled-by-default-linters) `goimports` is not enabled. As you are using a build tag on this file, this file is excluded by default.

**Comment by acabarbaye** [comment]
Please find below the content of my `.golangci.yaml`
```
run:
  timeout: 10m

  # Run linters over integration tests
  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - stylecheck
    - gosec
    - goimports
    - gci

linters-settings:
  goimports:
    local-prefixes: github.com/***
  gci:
    local-prefixes: github.com/***
```
