### ISSUE TITLE
goimports -local not enforced

### ISSUE THREAD

**Issue by j0hnsmith** [golangci/golangci-lint#2251]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

`golangci-lint run` doesn't fail or highlight any errors yet when I run `find . -name '*.go' | xargs goimports -d -local 'github.com/org/repo' -w` changes to the ordering of imports are made. I expect `golangci-lint run` to fail (and highlight the import ordering proglems).

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
...
linters:
  disable-all: true
  enable:
    - goimports
    ...

linters-settings:
  goimports:
    local-prefixes: github.com/org/repo
...
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17 darwin/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# no output
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
Hello, can you provide a reproducible example?

**Comment by j0hnsmith** [comment]
main.go
```go
package main

import (
	"github.com/kr/pretty"
	"fmt"
)

func main() {
	foo := "bar"
	fmt.Println(foo)
	pretty.Println(foo)
}
```

go.mod
```
module golangci-goimports

go 1.17

require github.com/kr/pretty v0.3.0

require (
	github.com/kr/text v0.2.0 // indirect
	github.com/rogpeppe/go-internal v1.6.1 // indirect
)
```

.golangci-lint.yaml
```yaml
linters:
  disable-all: true
  enable:
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/kr/pretty
```

running `golangci-lint run` doesn't find any problems however running `goimports -d -local 'github.com/kr/pretty' main.go` changes the imports in `main.go`, output

```diff
diff -u main.go.orig main.go
--- main.go.orig        2021-09-21 11:30:40.000000000 +0100
+++ main.go     2021-09-21 11:30:40.000000000 +0100
@@ -1,8 +1,9 @@
 package main
 
 import (
-       "github.com/kr/pretty"
        "fmt"
+
+       "github.com/kr/pretty"
 )
 
 func main() {
```

**Comment by ldez** [comment]
I don't reproduce your problem.
```console
$ golangci-lint run
main.go:4: File is not `goimports`-ed with -local github.com/kr/pretty (goimports)
        "github.com/kr/pretty"
```

note that the configuration filename must be `.golangci.yml` and not `.golangci-lint.yaml`

**Comment by j0hnsmith** [comment]
Above was a typo, but I had the file as `.golangci.yaml` instead of `.golangci.yml`, once I fix it I get the error. It's weird that I see this problem in ci though, guessing something is misconfigured. Sorry for wasting your time.

**Comment by marchelbling** [comment]
FWIW I just solved a similar issue. The problem was that we had an inconsistency:

* using an "allow list" to select linters i.e.
```
linters:
  disable-all: true
  enable:
    - goconst
    // goimports is missing here
```

* yet we had a configuration for `goimports`
```
linters-settings:
  goconst:
    min-len: 8
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/algolia/go
```

I wonder if there could be a flag that reports inconsistencies in the configuration as it's somewhat easy to miss this kind of problems.

**Comment by marchelbling** [comment]
FWIW I just solved a similar issue. The problem was that we had an inconsistency:

* using an "allow list" to select linters i.e.
```
linters:
  disable-all: true
  enable:
    - goconst
    // goimports is missing here
```

* yet we had a configuration for `goimports`
```
linters-settings:
  goconst:
    min-len: 8
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/org/repo
```

I wonder if there could be a flag that reports inconsistencies in the configuration as it's somewhat easy to miss this kind of problems.
