### ISSUE TITLE
Compatibility with Go 1.18

### ISSUE THREAD

**Issue by pierrre** [golangci/golangci-lint#2414]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

Go 1.18beta1 has been released.
When I run `golangci-lint run`
I get
```
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
```

</details>
But I'm using v1.43, installed with `curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0`.

### Configuration file

<details>

```console
$ cat .golangci.yml
```

</details>

I'm not using any config file

### Go environment

<details>

```console
$ go version && go env
go version go1.18beta1 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pierre/.cache/go-build"
GOENV="/home/pierre/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/pierre/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/pierre/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/pierre/.gimme/versions/go1.18beta1.src"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/pierre/.gimme/versions/go1.18beta1.src/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18beta1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2019785836=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment]
It's not an issue with go-critic/ruleguard than golangci-lint.

I recommend opening an issue on the [go-critic](https://github.com/go-critic/go-critic) repo.

**Comment by pierrre** [comment]
Very strange, I've got exactly the same error messages as
https://github.com/go-critic/go-critic/issues/1157
https://github.com/golangci/golangci-lint/issues/2374

**Comment by Goldziher** [comment]
Well, I am using 1.18beta2, and this is still an issue. Furthermore, I cannot bypass it by disabling go-ciritc in the golangci-lint configs, because it seems its always loaded no matter what. This is my config:

```yaml
linters-settings:
  goimports:
    local-prefixes: github.com/StreamElements/
  govet:
    check-shadowing: true
linters:
  disable:
    - gocritic
  enable:
    - bidichk
    - deadcode
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - goimports
    - goconst
    # - gocritic
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ineffassign
    - gosimple
    - govet
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
issues:
  fix: true
```

And this is what I am getting on the command line (running using pre-commit):

```shell
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	/Users/naamanhirschfeld/.cache/pre-commit/reposlmx3ef2/golangenv-default/pkg/mod/github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x52c
```
