### ISSUE TITLE
Allow to disable tests checking only for particular linters

### ISSUE THREAD

**Issue by ulexxander** [golangci/golangci-lint#2527]
### Your feature request related to a problem? Please describe.

Currently you can only enable all linters for tests or disable all linters for tests.

You can't enable/disable specific linter for tests.

https://golangci-lint.run/usage/configuration/#run-configuration

```yml
  # Include test files or not.
  # Default: true
  tests: false
```

In my case I would like my test files to be checked by all linters I have enabled, except one - `funlen`.

### Describe the solution you'd like.

Add `test-*` flavours of already existing settings inside `linters` configuration: disable-all, enable-all, disable, enable.

```yml
run:
  # Leave existing less flexible setting for compatibility.
  # Setting it to false will be equivalent to linters.tests-disable-all=true.
  # Setting it to true will be equivalent to linters.tests-enable-all=true.
  tests: false

linters:
  # New settings (overrides for tests):
  # Disable all linters for tests.
  tests-disable-all: true
  # Enable all linters for tests.
  tests-enable-all: true
  # Disable specific linters only for tests.
  tests-disable:
    - funlen
    - wrapcheck
  # Enable specific linters only for tests.
  tests-enable:
    - godox
```

### Describe alternatives you've considered.

Alternative solution may be to add field `tests: true/false` to each linter-specific config:

```yml
linters-settings:
  errchkjson:
    tests: false
```

**Comment by ldez** [comment]
Hello,

to disable one or several linters for tests you just have to add them to the `exclude-rules`.

ex:
```yml
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - goconst
```
