### ISSUE TITLE
unable to find 'latest' - use 'latest'

### ISSUE THREAD

**Issue by rexagod** [golangci/golangci-lint#2960]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

```
golangci/golangci-lint crit unable to find 'latest' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```

Logs: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/red-hat-storage_mcg-osd-deployer/58/pull-ci-red-hat-storage-mcg-osd-deployer-main-lint/1542483503499710464#1:build-log.txt%3A25

Somewhat similar: https://github.com/golangci/golangci-lint/issues/923

### Version of golangci-lint

`latest`: https://github.com/red-hat-storage/mcg-osd-deployer/pull/59/files

### Configuration file

```
run:
  concurrency: 8
  go: "1.17"
output:
  sort-results: true
  format: tab
issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//.kubebuilder:.*"
    - linters:
        - varnamelen
      text: "variable name 'r'"
    - linters:
        - gosec
      text: "G101: "
    - linters:
        - gomoddirectives
      text: "replacement"
  fix: true
linters-settings:
  lll:
    line-length: 120
  gci:
    no-inline-comments: true
    no-prefix-comments: true
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
```

### Go environment

`golang-1.17`: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/red-hat-storage_mcg-osd-deployer/58/pull-ci-red-hat-storage-mcg-osd-deployer-main-lint/1542483503499710464#1:build-log.txt%3A6

### Verbose output of running

`N/A` (LMK if needed and I'll log this from the CI)

### Code example or link to a public repository

[red-hat-storage/mcg-osd-deployer](https://github.com/red-hat-storage/mcg-osd-deployer)
