### ISSUE TITLE
gci: Prefixes with capital letters are ignored

### ISSUE THREAD

**Issue by acabarbaye** [golangci/golangci-lint#2985]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

The regression is with imports containing capital letters:
https://github.com/daixiang0/gci/issues/79

### Version of golangci-lint

1.4.7

### Configuration file
```
run:
  timeout: 10m

  build-tags:
    - integration

linters:
  disable-all: true # Disable defaults, then enable the ones we want
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - stylecheck
    - gosec
    - goimports
    - gci

linters-settings:
  goimports:
    local-prefixes: github.com/ARM-software
  gci:
    local-prefixes: github.com/ARM-software
```
### Go environment

1.18

### Verbose output of running

infinite loop

### Code example or link to a public repository

see https://github.com/daixiang0/gci/issues/79
