### ISSUE TITLE
missing config allow-leading-space for nolintlint

### ISSUE THREAD

**Issue by vincentscdc** [golangci/golangci-lint#3063]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

the setting allow-leading-space for nolintlint is not part of the NoLintLint settings

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# 1.48.0
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
```

```toml
[linters-settings.nolintlint]
require-explanation = true
require-specific = true
allow-leading-space = true
```

</details>

### Go environment

<details>

```console
$ go version && go env
# go1.19
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# unneeded
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by nhatthm** [comment]
Same here.

I use this configuration

```
linters-settings:
  nolintlint:
    # Disable to ensure that nolint directives don't have a leading space.
    # Default: true
    allow-leading-space: false
```

however `golangci-lint` still reports issues with `// nolint...`
