### ISSUE TITLE
The gofumpt linting rule implicitly assumes that Go 1.19 is being used

### ISSUE THREAD

**Issue by adamroyjones** [golangci/golangci-lint#3175]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

In short, I believe the gofumpt linting rule implicitly assumes that Go 1.19 is being used; this makes it awkward to work with the linting rule when using Go 1.18, since a parallel toolchain needs to exist just to pass files through `gofumpt`.

The below contains examples that should reproduce the problem.

#### The behaviour of `gofumpt` depends on the minor version of Go

Firstly: the behaviour of `gofumpt` depends on the version of Go being used. For example, take the following files:

```go
// main.go
package main

// Hello, world.
//
// - This will be modified by `gofumpt` if the version of Go is 1.19, but not
//   if the version is 1.18.
func main() {
}
```

```yaml
# docker-compose.yml
services:
  gofumpt18:
    image: golang:1.18-bullseye
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/

  gofumpt19:
    image: golang:1.19-bullseye
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/
```

Then run:

```sh
docker compose up -d

docker compose exec gofumpt18 bash
go install mvdan.cc/gofumpt@latest
gofumpt -d /go/src/main.go # No differences.
exit

docker compose exec gofumpt19 bash
go install mvdan.cc/gofumpt@latest
gofumpt -d /go/src/main.go # Differences.
exit
```

#### `golangci-lint` implicitly assumes that Go 1.19 is being used with the gofumpt linting rule

As well as the files above, add the following file:

```yaml
# .golangci.yml
run:
  go: '1.18'
linters:
  enable:
    - gofumpt
```

Then:

```sh
docker compose up -d

docker compose exec gofumpt18 bash
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
  | sh -s -- -b $(go env GOPATH)/bin 
cd /go/src
go mod init reprex
golangci-lint run # Produces errors.
rm go.mod
exit
```

### Version of golangci-lint

The reproducing example above used, at the time of writing, version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z.

### Configuration file

See above.

### Go environment

This is captured within the containers above.

### Verbose output of running

This is captured within the containers above.

### Code example or link to a public repository

See above.
