### ISSUE TITLE
ERRO Running error: context loading failed: failed to load program with go/packages: go list repeated package internal/singleflight with different values

### ISSUE THREAD

**Issue by shuxiao9058** [golangci/golangci-lint#335]
as titled.

**Comment by alexkohler** [comment]
Can you include what you were trying to accomplish, an example, version, config file, etc? See the issue template:

```
1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
2. Config file: `cat .golangci.yml`
3. Go environment: `go version && go env`
4. Verbose output of running: `golangci-lint run -v`
```

**Comment by shuxiao9058** [comment]
- Version
 install with brew, golangci-lint has version 1.12.5 built from 609de32 on 2018-12-23T09:40:14Z
- Config file
```
# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  # tests: true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  # build-tags:
  #   - mytag

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - .git
    - src/git.alenshaw.com/
    - .*/go-redis/
    # - src/external_libs
    # - autogenerated_by_my_lib

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  skip-files:
    - ".*\\.my\\.go$"
    - libmte\\.a
    - lib/bad.go

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  # modules-download-mode: readonly|release|vendor
  modules-download-mode: ''


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*,mt:.*

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    # exclude: /path/to/file.txt
  govet:
    # report about shadowed variables
    check-shadowing: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    # local-prefixes: github.com/org/project
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
     github.com/go-redis/redis
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  unparam:
    # call graph construction algorithm (cha, rta). In general, use cha for libraries,
    # and rta for programs with main packages. Default is cha.
    algo: cha

    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 30
  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.

    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  gocritic:
    # which checks should be enabled; can't be combined with 'disabled-checks';
    # default are: [appendAssign assignOp caseOrder dupArg dupBranchBody dupCase flagDeref
    # ifElseChain regexpMust singleCaseSwitch sloppyLen switchTrue typeSwitchVar underef
    # unlambda unslice rangeValCopy defaultCaseOrder];
    # all checks list: https://github.com/go-critic/checkers
    # enabled-checks:
    #   - rangeValCopy
    # which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - deadcode

    # settings: # settings passed to gocritic
    #   captLocal: # must be valid enabled check name
    #     checkLocals: true
    #   rangeValCopy:
    #     sizeThreshold: 32

linters:
  # enable:
   #  - megacheck # so check
   # - govet
  enable-all: true
  disable:
    - megacheck
  # disable:
  #   - maligned
  #   - prealloc
  # disable-all: true
  # presets:
  #   - bugs
  #   - unused
  fast: true


# issues:
#   # List of regexps of issue texts to exclude, empty list by default.
#   # But independently from this option we use default exclude patterns,
#   # it can be disabled by `exclude-use-default: false`. To list all
#   # excluded by default patterns execute `golangci-lint run --help`
#   exclude:
#     - abcdef

#   # Independently from option `exclude` we use default exclude patterns,
#   # it can be disabled by this option. To list all
#   # excluded by default patterns execute `golangci-lint run --help`.
#   # Default value for this option is true.
#   exclude-use-default: false

#   # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
#   max-per-linter: 0

#   # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
#   max-same-issues: 0

#   # Show only new issues: if there are unstaged changes or untracked files,
#   # only those changes are analyzed, else only changes in HEAD~ are analyzed.
#   # It's a super-useful option for integration of golangci-lint into existing
#   # large codebase. It's not practical to fix all existing issues at the moment
#   # of integration: much better don't allow issues in new code.
#   # Default is false.
#   # new: false

#   # Show only new issues created after git revision `REV`
#   # new-from-rev: REV

#   # Show only new issues created in git patch with set file path.
#   # new-from-patch: path/to/patch/file

```
- Go environment
```
 go version && go env                                                                                                                                                                                                          (feature/opt_qp|…
go version go1.11.4 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jiya/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/usr/local/gopath"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zz/kq305wt53jx650qz4dmn7r8h0000gn/T/go-build052429706=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
- Verbose output

```
NFO [config_reader] Config search paths: [./ ... /Users/jiya/workspace /Users/jiya /Users /]
INFO [config_reader] Used config file ../../../.config/golangci-lint/golangci.yml
INFO Gocritic enabled checks: [appendAssign assignOp caseOrder dupArg dupBranchBody dupCase flagDeref ifElseChain singleCaseSwitch sloppyLen switchTrue typeSwitchVar underef unlambda unslice defaultCaseOrder]
INFO [lintersdb] Active 25 linters: [deadcode depguard dupl errcheck gochecknoglobals gochecknoinits goconst gocritic gocyclo gofmt goimports golint gosec govet ineffassign lll maligned misspell nakedret prealloc scopelint structcheck typecheck unconvert varcheck]
INFO [loader] Go packages loading at mode load types and syntax took 3.042755442s
ERRO Running error: context loading failed: failed to load program with go/packages: go list repeated package internal/singleflight with different values
INFO Memory: 33 samples, avg is 69.2MB, max is 69.2MB
INFO Execution took 3.259166769s
```
