### ISSUE TITLE
Example go-critic options are invalid

### ISSUE THREAD

**Issue by jirfag** [golangci/golangci-lint#382]
Example go-critic options are invalid, need to check it. Also we need to run linter with the example config file and check it runs successfully.

```
gocritic:
    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        checkLocals: true
      rangeValCopy:
        sizeThreshold: 512
      hugeParam:
        sizeThreshold: 512
```
