### ISSUE TITLE
add option -i(ignore) to misspell linter

### ISSUE THREAD

**Issue by hgsgtk** [golangci/golangci-lint#384]
I wanted to use misspell linter, however to use misspell we have to set ignore option `-i`.
Do you have a plan to add ignore option? Or Can I challenge to add ignore option to golangci-lint?

```
  -i string
    	ignore the following corrections, comma separated
```
https://github.com/client9/misspell

1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
https://github.com/golangci/golangci-lint/commit/7b2421d55194c9dc385eff7720a037aa9244ca3c

2. Config file: `cat .golangci.yml`

```
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - dupl
    - lll
    - goconst
    - depguard
    - goimports
    - misspell
    - scopelint
    - gosec
```
3. Go environment: `go version && go env`
go version go1.11 darwin/amd64
4. Verbose output of running: `golangci-lint run -v`
