### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by tbarbugli** [golangci/golangci-lint#3925]
### Your feature request related to a problem? Please describe.

Golangci is much slower than the linters it wraps

### Describe the solution you'd like.

I think the shared analysis step makes sense but it seems to be incredibly slow, I see a 20x slow down between gocritic and the same with golanci

### Describe alternatives you've considered.

Tried tuning params of all kind, unfortunately I have no time to dive into it more than that

**Comment by ldez** [comment]
Hello,

Can you provide a reproducible context?

**Comment by guerinoni** [comment]
Tested on repo `docker/compose`

```bash
√ compose v2 % time gocritic check
gocritic check  0.37s user 0.16s system 177% cpu 0.297 total
```

```bash
√ compose v2 % golangci/1.52.2/golangci-lint cache clean
√ compose v2 % time golangci/1.52.2/golangci-lint run
golangci/1.52.2/golangci-lint run  1.79s user 1.50s system 231% cpu 1.421 total
```

```yml
run:
  concurrency: 2
  timeout: 10m
linters:
  enable-all: false
  disable-all: true
  enable:
    - gocritic
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - style
    disabled-checks:
      - paramTypeCombine
      - unnamedResult
      - whyNoLint
```
