### ISSUE TITLE
padding check

### ISSUE THREAD

**Issue by kehiy** [golangci/golangci-lint#4011]
### Your feature request related to a problem? Please describe.

you can add a feature to check the padding alignment of structs in code and suggest a better way for optimize memory usage

### Describe the solution you'd like.

nothing

### Describe alternatives you've considered.

nothing

**Comment by bombsimon** [comment]
You mean like [`fieldalignment`](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment)? That's included via `govet`, see https://golangci-lint.run/usage/linters/#govet

```yaml
linters-settings:
  govet:
    enable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - govet
 ```
