### ISSUE TITLE
--new-from-rev gets confused by merge commits

### ISSUE THREAD

**Issue by mering** [golangci/golangci-lint#4097]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Adding a reproduction example to demonstrate breakage of #4047.

### Version of golangci-lint

<details>

```console
$ ./golangci-lint --version
# 1.54.2
```

</details>

### Configuration

_No configuration file_

<details>

```console
--new-from-rev <sha of 1 commit before HEAD>
```

</details>

### Go environment

_Using binary_

### Verbose output of running

Running with `--new-from-rev HEAD~1` doesn't show anything even though an unused variable was introduced in the last commit when an error already existed before a merge commit. When adding changes in unrelated files it shows all problems even though some of them have been introduced before.

### A minimal reproducible example or link to a public repository

<details>

```sh
#!/bin/sh
set -x

REPO="rev-binary"
git init "$REPO" && pushd $_
echo golangci-lint > .gitignore
GOLANGCI_LINT_VERSION="1.54.2"
curl -Lf https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz | tar xz -C . --strip-components=1 && chmod +x ./golangci-lint
git add .
git commit -m "chore: initial empty commit."

go mod init github.com/gcl/example 
git add .
git commit -m "chore: setup project"

cat <<EOF > foo.go
package pkg

func foo() {
    unusedVariableInFoo := 0
}
EOF
git add .
git commit -m "introduced unused var"

git diff HEAD~1
./golangci-lint run
./golangci-lint run --new-from-rev HEAD~1

git checkout -b b1
git commit -m "empty b1" --allow-empty
git switch -
git merge b1 --no-ff --no-edit

cat <<EOF >> foo.go

func foo2() {
    unusedVariableInFoo2 := 0
}
EOF
git add .
git commit -m "another prob"

git diff HEAD~1
./golangci-lint run
# NOTE the following command doesn't print anything although it should print the problem within bar()
./golangci-lint run --new-from-rev HEAD~1

cat <<EOF > bar.go
package pkg

func bar() {
    unusedVariableInBar := 0
}
EOF
git add .
git commit -m "another prob"

git diff HEAD~1
./golangci-lint run
# NOTE the following command also prints the problems in foo.go although this file didn't change in the last commit
./golangci-lint run --new-from-rev HEAD~1

echo "Cleanup"
popd
rm -rf "$REPO"
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
Hello,

> [x]  Yes, I'm using a binary release within 2 latest major releases.

Have you tried with previous versions?

is there a difference?

**Comment by mering** [comment]
Which version do you want me to try? I tried 1.50.0 for example with the same result.
You can easily change the version string in the repro script yourself and just run it.

**Comment by udaya2899** [comment]
Hi @ldez, friendly reminder. Can you help us with this please?

**Comment by ldez** [comment]
This is how git works, so I have no magic solution.

**Comment by mering** [comment]
> This is how git works, so I have no magic solution.

Can you elaborate on which part of Git workings you are referring to? To me the git diff looks as expected but `golangci-lint` doesn't interpret the diff correctly.

**Comment by faximan** [comment]
@ldez ping!

**Comment by janwytze** [comment]
I think I'm currently running in the same problem when using golangci-lint in Gitlab merge result pipielines. This is my CI stage:

```
lint:
  image: golangci/golangci-lint:latest-alpine
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME && git branch $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -f remotes/origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git diff HEAD $CI_MERGE_REQUEST_TARGET_BRANCH_NAME # Works, and gives back files and lines that do contain linting errors.
    - golangci-lint run --new-from-rev $CI_MERGE_REQUEST_TARGET_BRANCH_NAME # No result, this same command works locally.
```

Locally it works fine, but within merge result pipelines it does not work :(
