### ISSUE TITLE
go-critic: support to enable/disable all checks

### ISSUE THREAD

**Issue by Dentrax** [golangci/golangci-lint#4108]
### Your feature request related to a problem? Please describe.

We have to manually define all the checks in the config: https://go-critic.com/overview.html It's a bit annoying to manage all of the _checks_ individually.

Ref: https://golangci-lint.run/usage/linters/#gocritic

### Describe the solution you'd like.

Add support for `enable-all: true` and `disable-all: true` for `gocritic`. So that I can drop unwanted checks in the `disabled-checks` section.

### Describe alternatives you've considered.

As-is. Manually define and manage all the checks.

**Comment by nemre** [comment]
+1

**Comment by ferhatelmas** [comment]
As a workaround, you can add [all tags](https://github.com/go-critic/go-critic/blob/master/linter/linter.go#L14) (which are only 6 of them but `security` not working yet) and then disable what you don't want.

**Comment by GreyXor** [comment]
Doing it like so:
```yaml
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
```
