### ISSUE TITLE
Running v1.56.0 version throws panics, v1.55.2 works fine

### ISSUE THREAD

**Issue by maksim-paskal** [golangci/golangci-lint#4361]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Running today latest version
```bash
go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.0 run -v
````
throws panics
```
ERRO Running error: can't run linter goanalysis_metalinter
goanalysis_metalinter: interfacer: package "main" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
```

```yaml
#.golangci.yml
run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - gochecknoglobals
  - exhaustivestruct
  - exhaustruct
  - varnamelen
  - musttag
  - depguard
```

### Version of golangci-lint

<details>

```console
> go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.0 --version
golangci-lint has version v1.56.0 built with go1.21.5 from (unknown, mod sum: "h1:uivqYQ8WbkWAE4LgjLLhxsTyb68FlcZF3ZIF0oyn4WQ=") on (unknown)
```

</details>

### Configuration

<details>

```yaml
run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - gochecknoglobals
  - exhaustivestruct
  - exhaustruct
  - varnamelen
  - musttag
  - depguard
```

</details>

### Go environment

<details>

```console
go version go1.21.5 darwin/amd64
```

</details>

### Verbose output of running

<details>

```console
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: interfacer: package "client" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
INFO [runner] processing took 3.335µs with stages: max_same_issues: 502ns, uniq_by_line: 411ns, skip_dirs: 334ns, nolint: 287ns, cgo: 203ns, source_code: 133ns, autogenerated_exclude: 130ns, filename_unadjuster: 127ns, fixer: 125ns, identifier_marker: 125ns, skip_files: 125ns, exclude: 125ns, path_prettifier: 120ns, exclude-rules: 119ns, max_from_linter: 111ns, diff: 67ns, path_shortener: 60ns, sort_results: 60ns, severity-rules: 59ns, max_per_file_from_linter: 58ns, path_prefixer: 54ns 
INFO [runner] linters took 16.579660199s with stages: goanalysis_metalinter: 16.579591126s 
ERRO Running error: can't run linter goanalysis_metalinter
goanalysis_metalinter: interfacer: package "client" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference 
INFO Memory: 168 samples, avg is 1038.6MB, max is 1648.4MB 
INFO Execution took 17.114056017s  
```

</details>

### A minimal reproducible example or link to a public repository

<details>

https://github.com/maksim-paskal/aks-node-termination-handler

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment]
hello,

interfacer is deprecated.

Can you add this to your configuration?

```yml
linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - varnamelen
    - musttag
    - depguard
```

**Comment by maksim-paskal** [comment]
@ldez thanks for quick answer, yes it helps

Do I need to add all deprecated linters now in my configuration?

**Comment by ldez** [comment]
I tried your repository and my suggestion fix your problem.

Interfacer is a very very old linter, deprecated for years.

> Do I need to add all deprecated linters now in my configuration?

yes

**Comment by maksim-paskal** [comment]
@ldez how about `disable-deprecated: true`?
```yaml
#.golangci.yml
run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable-deprecated: true
  disable:
  - gochecknoglobals
  - exhaustivestruct
  - exhaustruct
  - varnamelen
  - musttag
  - depguard
```

I try to use all new linters by default. I did not pay attention to deprecated linters, perhaps other users do the same.
