### ISSUE TITLE
revive: forward Exclude rule config

### ISSUE THREAD

**Issue by sapphire-janrain** [golangci/golangci-lint#4364]
### Your feature request related to a problem? Please describe.

Right now I'm using issues.exclude-rules to achieve what I want to do, but it would be nice if there was a way to just provide the exclusion to revive directly via [the Exclude config option](https://github.com/mgechev/revive/blob/5c5d6c1075a82337d9840e7f8195c0eaccdb959c/lint/config.go#L15)

### Describe the solution you'd like.

```yaml
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        exclude: ["TEST"]
        # TEST is a magic word in revive to filter out test files,
        # no special handling needed in golangci-lint
```

### Describe alternatives you've considered.

issues.exclude-rules

**Comment by ldez** [comment]
Hello,

The test files are filtered before the analysis by the linter with the option `run.test`:
https://golangci-lint.run/usage/configuration/#run-configuration

This can lead to really unexpected situations.

I will implement support for this option even if I think this will lead to comprehension problems.

I understand you already use `issues.exclude-rules` but I recommend using something like this:

```yml
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - revive
      text: "^(unused-parameter|add-constant)"
```
