### ISSUE TITLE
How to pass options to specific linters? or how to exclude multiple rules for one linter?

### ISSUE THREAD

**Issue by lnshi** [golangci/golangci-lint#475]
1. How to pass options to specific linter? I did like below, unfortunately it doesn't work:
```
linters-settings:
  gosec:
    settings:
      exclude: "G401", "G501"
```

2. How to exclude multiple rules for one linter, I did like below, unfortunately it doesn't work:
```
issues:
  exclude-rules:
    - linters:
      - gosec
      text:
        - "G501: Blacklisted import `crypto/md5`: weak cryptographic primitive"
        - "G401: "
```

A bit confused by the configuration way: one text with `linters` array, should not that one linter with text array make more sense?
