### ISSUE TITLE
exhaustive use too many memory

### ISSUE THREAD

**Issue by trim21** [golangci/golangci-lint#5065]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

I'm running golangci-lint with disable-all and `enable: [exhaustive]`

It use also all memory and can't complete its running.

![image](https://github.com/user-attachments/assets/79c61c55-2c94-42bf-bf71-e6165ef685dc)
![image](https://github.com/user-attachments/assets/7d04a56f-e8cb-4d5b-8f48-6b8d9272a8be)

with upstream project, it works fine with ` exhaustive -default-signifies-exhaustive ./...`

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.59.1 built with go1.22.3 from 1a55854a on 2024-06-09T18:08:33Z
```

</details>

### Configuration

<details>

```console
golangci-lint run
```

I'm trying it on https://github.com/golangci/golangci-lint itself, with only `linters` and `linters-settings` changed.

```yaml
linters:
  disable-all: true
  # This list of linters is not a recommendation (same thing for all this configuration file).
  # We intentionally use a limited set of linters.
  # See the comment on top of this file.
  enable:
    - exhaustive


linters-settings:
  exhaustive:
    # check switch statements in generated files also
    check-generated: false
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.23.1 windows/amd64
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Trim21\AppData\Local\go-build
set GOENV=C:\Users\Trim21\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Trim21\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Trim21\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Users\Trim21\.g\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=C:\Users\Trim21\AppData\Local\Temp\go
set GOTOOLCHAIN=local
set GOTOOLDIR=C:\Users\Trim21\.g\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.1
set GODEBUG=
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\Trim21\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Trim21\proj\golangci-lint\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Trim21\AppData\Local\Temp\go\go-build3112247659=/tmp/go-build -gno-record-gcc-switches
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

https://github.com/trim21/golangci-lint/tree/bug-5065

branch bug-5065 with config above

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)
