### ISSUE TITLE
Unexpected gci linter error after upgrading to v1.63.0

### ISSUE THREAD

**Issue by xeptore** [golangci/golangci-lint#5273]
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

After [upgrading to v1.63.0](https://github.com/xeptore/linkos/commit/06cd0d23e92738cfbb93286e16763fa01f785043), `gci` linter fails with the following error message:
```txt
iphlpapi\api.go:10:1: File is not properly formatted (gci)
*/
^

exit status 8
task: Failed to run task "lint:ci": exit status 1
```
Failing workflow job: <https://github.com/xeptore/linkos/actions/runs/12569153432/job/35037538483>
Failing workflow job raw log: archive (specifically, `Lint Client` job): 
[logs_32589747240.zip](https://github.com/user-attachments/files/18285875/logs_32589747240.zip)

Workflow run before the upgrade: <https://github.com/xeptore/linkos/actions/runs/12569153432/job/35037538483>
Successful workflow job raw log archive before the upgrade:
[logs_32584257385.zip](https://github.com/user-attachments/files/18285880/logs_32584257385.zip)

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.63.0 built with go1.23.4 from (unknown, modified: ?, mod sum: "h1:4HZnKnU9nA08TQpzpl5Ngrr79B/tEvv0UJVZ92K0k1k=") on (unknown)
```

</details>

### Configuration

<details>

Same config file used before and after the upgrade: <https://github.com/xeptore/linkos/blob/bf3340c97fb54bfc339bccc0c97b50105a3d2cc6/.golangci.yaml>

```yml
run:
  issues-exit-code: 8
  timeout: 10m
linters:
  disable:
    - cyclop
    - contextcheck
    - depguard
    - dupl
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - err113
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
linters-settings:
  errorlint:
    errorf: false
    errorf-multi: true
    asserts: true
    comparison: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/xeptore/linkos)
    skip-generated: false
  gosec:
    excludes:
      - G601
  nlreturn:
    block-size: 1
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: snake
        envconfig: upperSnake
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.23.4 windows/amd64
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Hasbi\AppData\Local\go-build
set GOENV=C:\Users\Hasbi\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=D:\dev\env\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\dev\env\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\dev\env\go\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=D:\dev\env\go\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.23.4
set GODEBUG=
set GOTELEMETRY=off
set GOTELEMETRYDIR=C:\Users\Hasbi\AppData\Roaming\go\telemetry
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=clang
set CXX=clang++
set CGO_ENABLED=1
set GOMOD=NUL
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\Hasbi\AppData\Local\Temp\go-build3881085242=/tmp/go-build -gno-record-gcc-switches
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

Cleaned cache. Let me know if you need another workflow run with `-v` flag set.

</details>

### A minimal reproducible example or link to a public repository

<details>

Failing file: <https://github.com/xeptore/linkos/blob/bf3340c97fb54bfc339bccc0c97b50105a3d2cc6/iphlpapi/api.go>
Before/after upgrade workflow links/logs are provided above.

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)
