### ISSUE TITLE
🌟 Let's talk about output formats options

### ISSUE THREAD

**Issue by ldez** [golangci/golangci-lint#5364]
> [!IMPORTANT]
> This is a proposal: I don't know if it is possible and what the impact could be inside the code.
> The proposal may evolve.

---

<details>
<summary>The current configuration</summary>

```yml
# colored-line-number
# line-number
# json
# colored-tab
# tab
# html
# checkstyle
# code-climate
# junit-xml
# junit-xml-extended
# github-actions
# teamcity
# sarif

output:
  print-issued-lines: false
  print-linter-name: false
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
```

```ini
--out-format=checkstyle:report.xml,json:stdout,line-number-colored
--print-issued-lines=false
--print-linter-name=false
```

</details>

---

### Global Options but Only For Some Formats

```yml
output:
  print-issued-lines: false
  print-linter-name: false
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
```

- The option `output.print-issued-lines` is for `line-number`, `colored-line-number` formats.
- The option `output.print-linter-name` is for `line-number`, `colored-line-number`, `tab`, `colored-tab` formats.

### Format Names

The names of the colored variants have an unexpected style:
- `line-number`, `colored-line-number`
- `tab`, `colored-tab`

I think `tab`, `tab-colored` are more natural.

### Slice of Formats

```yml
output:
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
```

Currently, the formats are represented into a slice, this type has been introduced mainly for compatibility reasons with the initial `format` option (a simple string)

A side effect of a slice is the possibility of defining the same format several times but with different output paths.
But I think this is not a real use case.

Another side effect is the flag parsing complexity because the flag `--out-format` value is a simple string.

### Non-User friendly CLI flag

The current syntax can be used only if you know the syntax and there is no suggestion/completion.

```ini
--out-format=checkstyle:report.xml,json:stdout,line-number-colored
```

### Configuration

```yml
output:
  formats:
    text: # (line-number)
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
    json:
      path: ./path/to/output.json
    tab:
      path: stdout
      print-linter-name: true
      colors: true
    html:
      path: ./path/to/output.html
    checkstyle:
      path: ./path/to/output.xml
    code-climate:
      path: ./path/to/output.json
    junit-xml:
      path: ./path/to/output.xml
      extended: true
    teamcity:
      path: ./path/to/output.txt
    sarif:
      path: ./path/to/output.json
```

### CLI flags

```ini
--output.text.path=stdout
--output.text.print-linter-name=false
--output.text.print-issued-lines=false
--output.text.colors=false
--output.json.path=./path/to/output.json
--output.tab.path=stdout
--output.tab.print-linter-name=false
--output.tab.colors=false
--output.html.path=./path/to/output.html
--output.checkstyle.path=./path/to/output.xml
--output.code-climate.path=./path/to/output.json
--output.junit-xml.path=./path/to/output.xml
--output.junit-xml.extended=true
--output.teamcity.path=./path/to/output.txt
--output.sarif.path=./path/to/output.json
```

<details>
<summary>example</summary>

Before:
```ini
--out-format=checkstyle:report.xml,json:stdout,line-number-colored
```

After:
```ini
--output.checkstyle.path=report.xml
--output.json.path=stdout
--output.text.path=stdout
```

</details>

**Comment by ldez** [comment]
I created a working implementation.

As the main key `output.formats` is the same as the existing one, and the current implementation uses a hack to handle multiple types (string, slice), I didn't find a way to create a compatibility layer.

I wonder if the flag prefix `--output.` is right or not, I mean `--output.text.path` vs `--text.path`.

**Comment by ldez** [comment]
Maybe the new main key can be `output.styles` 🤔 

With the new `fmt` command it can be better to avoid the word `format` for linter 🤔

**Comment by bombsimon** [comment]
> I wonder if the flag prefix `--output.` is right or not, I mean `--output.text.path` vs `--text.path`.

> Maybe the new main key can be `output.styles` 🤔 
> 
> With the new `fmt` command it can be better to avoid the word `format` about elements related to linters 🤔 

I think the proposal looks good and would be an improvement from the current `--out-format`. By supporting multiple output formats at the same time it can become complex and messy with the flags rather than just having the user pipe to a file and us printing to stdout. And as long as we want to support all configs from a config file as CLI flags it will look something like your suggestion.

I think it's fine to (re)use `format` if you want to, don't see it as risk of ambiguity with the `fmt` "format".  I'd prefer it over `styles` at least.

But I also pondering if it would be possible to keep using `out-format` but improve the usage? Right now we don't have anything other than `format` at the second level in the config and it's completely omitted in the CLI flags so it's not a 1:1 map.

Thinking

```yaml
---
out-format:
  json:
    path: /tmp/out.json
  tab:
    colors: true
```

```sh
--out-format.json.path=/tmp.out.json
--out-format.tab.colors=true
```

In your example in the original post it seems like `line-number-colored` got dropped, where would that go? Something like `--output.line-number-colored`?

**Comment by ldez** [comment]
`line-number-colored` -> `text`

**Comment by ldez** [comment]
> But I also pondering if it would be possible to keep using out-format but improve the usage? 

I'm not a fan of `out-format`: this is weird to use `out` instead of `output`.

> I'd prefer it over `styles` at least.

Ok so I cannot create a compatibility layer, the PR will be open after the next minor release.

**Comment by ldez** [comment]
Note: I trimmed the configuration to only focus on `formats` but there are more fields.

```yml
output:
  path-prefix: ""
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
  # ...
```
