### ISSUE TITLE
Excessive memory use with staticcheck and gosimple

### ISSUE THREAD

**Issue by ulope** [golangci/golangci-lint#5449]
### Welcome

- [x] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### How did you install golangci-lint?

Official binary

### Description of the problem

After upgrading from `1.55.2` to `1.64.5` we got CI failures due to OOM kills.

Bisecting our enabled linters revealed that enabling either `staticcheck` or `gosimple` leads to excessive memory use. On my local machine I manually killed the process at around 34GB usage.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.64.5 built with go1.24.0 from 0a603e49 on 2025-02-13T21:19:55
```

</details>

### Configuration

<details>

```console
linters-settings:
  unparam:
    check-exported: true
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: github.com/sirupsen/logrus
            description: "Don't use"
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  forbidigo:
    forbid:
      - "pk\\b"
  funlen:
    lines: 100
    statements: 50
  gci:
    custom-order: true
    sections:
      - Standard
      - Default
      - Prefix(github.com/shutter-network/shutter)
      - Prefix(github.com/shutter-network/rolling-shutter)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
      - unnamedResult
      - rangeValCopy
      - typeDefFirst
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/shutter-network/shutter
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      # - name: exported
      # - name: if-return
      - name: increment-decrement
      #- name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: unnecessary-stmt
      - name: range-val-in-closure
      - name: atomic
      - name: superfluous-else

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    # - depguard
    # - unused
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - forbidigo
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - whitespace

  # don't enable:
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - goerr113
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
  # - godox

issues:
  exclude:
    - "typeUnparen: could simplify \\(func.* to func\\("
    - "Error return value of `.*Mark.*Flag.*` is not checked"
    - "Error return value of `viper.BindEnv` is not checked"
    - 'shadow: declaration of "err" shadows declaration at line'
    - "Expect WriteFile permissions to be"
    - "GobEncode - result 1 .* is always nil"
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - staticcheck
    - path: evtype/evtype\.go
      linters:
        - gosec
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

run:
  timeout: 10m
  skip-dirs:
    - test/testdata_etc
    - internal/cache
    - internal/renameio
    - internal/robustio
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

On CircleCI with 16GB ram limit:

```console
$ golangci-lint cache clean
$ base=`git merge-base HEAD origin/main`; \
golangci-lint --verbose run --concurrency 3 --print-resources-usage --new-from-rev ${base}
INFO golangci-lint has version 1.64.5 built with go1.24.0 from 0a603e49 on 2025-02-13T21:19:55Z 
INFO [config_reader] Config search paths: [./ /home/circleci/src/rolling-shutter /home/circleci/src /home/circleci /home /] 
INFO [config_reader] Used config file .golangci.yml 
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`. 
INFO [goenv] Read go env for 8.197797ms: map[string]string{"GOCACHE":"/home/circleci/.cache/go-build", "GOROOT":"/home/circleci/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.6.linux-amd64"} 
INFO [lintersdb] Active 31 linters: [bodyclose copyloopvar dogsled errcheck exhaustive forbidigo funlen gci goconst gocritic gocyclo godot gofumpt goprintffuncname gosec gosimple govet ineffassign lll misspell nakedret nilnesserr noctx nolintlint revive staticcheck stylecheck thelper unconvert unparam whitespace] 
INFO [loader] Go packages loading at mode 8767 (files|imports|name|compiled_files|deps|exports_file|types_sizes) took 23.426666103s 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 29.407177ms 
Killed
make: *** [Makefile:113: lint-changes] Error 137
```

</details>

### A minimal reproducible example or link to a public repository

<details>

Public repo (branch): https://github.com/shutter-network/rolling-shutter/tree/chore/upgrade-go-1.23.6
Run `make lint-changes`

</details>

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Based on [your log](https://app.circleci.com/pipelines/github/shutter-network/rolling-shutter/3309/workflows/715a1a1c-455a-47d4-b6c8-253f27f4aff3/jobs/29035) I think your problem is here, you have a compilation issue (`typecheck` errors).

**Comment by ulope** [comment]
This is with `staticcheck` and `gosimple` commented out (sorry should have mentioned this above).

**Comment by ldez** [comment]
I think you are not using the right Go version inside your CI.

https://github.com/shutter-network/rolling-shutter/blob/fd87d6ae09227a7719a22fb13ac0bad0cc6ca418/.circleci/config.yml#L39

https://github.com/shutter-network/rolling-shutter/blob/fd87d6ae09227a7719a22fb13ac0bad0cc6ca418/.circleci/config.yml#L32

**Comment by ldez** [comment]
> But should this matter?

Yes

> We're using the official binary build (via asdf).

I don't know how asdf packages the binaries.

> Do the go versions that golangci-lint was built with and the local project one have to match?

No but it should be consistent: golangci-lint uses some go commands (This is something inside the Go tooling)

**Comment by ldez** [comment]
This is a bit offtopic (and this has no impact no your problem) but I suggest to update your configuration:

<details>
<summary>.golanci.yml</summary>

```yml
linters-settings:
  unparam:
    check-exported: true
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: "Don't use"
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  forbidigo:
    forbid:
      - "pk\\b"
  funlen:
    lines: 100
    statements: 50
  gci:
    custom-order: true
    sections:
      - Standard
      - Default
      - Prefix(github.com/shutter-network/shutter)
      - Prefix(github.com/shutter-network/rolling-shutter)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
      - unnamedResult
      - rangeValCopy
      - typeDefFirst
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/shutter-network/shutter
  mnd:
      # don't include the "operation" and "assign"
      checks: 
        - argument
        - case
        - condition
        - return
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      # - name: exported
      # - name: if-return
      - name: increment-decrement
      #- name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: unnecessary-stmt
      - name: range-val-in-closure
      - name: atomic
      - name: superfluous-else

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - forbidigo
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - unconvert
    - unparam
    - whitespace

issues:
  exclude:
    - "typeUnparen: could simplify \\(func.* to func\\("
    - "Error return value of `.*Mark.*Flag.*` is not checked"
    - "Error return value of `viper.BindEnv` is not checked"
    - 'shadow: declaration of "err" shadows declaration at line'
    - "Expect WriteFile permissions to be"
    - "GobEncode - result 1 .* is always nil"
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - staticcheck
    - path: evtype/evtype\.go
      linters:
        - gosec
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

run:
  timeout: 10m
```

</details>


The command `golangci-lint config verify` can help you to detect configuration problems.
