### ISSUE TITLE
Disable a formatter for a path

### ISSUE THREAD

**Issue by corentinmusard** [golangci/golangci-lint#5625]
### Welcome

- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### How did you install golangci-lint?

Brew

### Your feature request related to a problem? Please describe

Can you make it possible to disable a specific formatter for a give path?

For linters we have
```yaml
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - linters:
          - containedctx
          - dogsled
        path: _test.go
```

Use case: I want to enable `golines` everywhere but not on my  `_test.go` files.

### Describe the solution you'd like

```yaml
formatters:
  enable:
    - golines
  exclusions:
    paths:
      - linters:
          - golines
        path: _test.go
```

### Describe alternatives you've considered

Keeping `golines` disabled

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Hello,

Currently, you cannot disable one formatter for a path, but you can exclude a path (for all formatters):

```yml
formatters:
  paths:
    - _test.go
```

Can you explain why you want to apply formatters expect one on a specific file?
