### ISSUE TITLE
Build failed with vendored modules on golangci.com

### ISSUE THREAD

**Issue by sashayakovtseva** [golangci/golangci-lint#579]
1. Version of golangci-lint: 
According to logs: `golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:06:49Z`

2. Config file: 
```
run:
  deadline: 3m

  build-tags:
    - selinux
    - seccomp

  modules-download-mode: vendor

linters:
  enable-all: true
  disable:
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - prealloc
    - errcheck

linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golang/glog.Verbose).Infof
          - github.com/golang/glog.Infof
          - github.com/golang/glog.Warningf
          - github.com/golang/glog.Errorf
          - github.com/golang/glog.Fatalf
          - github.com/golang/glog.Exitf
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20

  lll:
    tab-width: 4
  prealloc:
    simple: true


issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - lll
        - scopelint

    - path: pkg/server/runtime/streaming.go
      linters:
        - gocyclo

    - text: "vendor/github.com/kubernetes-sigs/cri-o/pkg/seccomp/seccomp.go"
      linters:
        - typecheck

    - path: pkg/server
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
```

3. Go environment: `go version && go env`
```
$ go version
    go version go1.11.5 linux/amd64
$ go env
    GOARCH="amd64"
    GOBIN=""
    GOCACHE="/root/.cache/go-build"
    GOEXE=""
    GOFLAGS=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/go"
    GOPROXY=""
    GORACE=""
    GOROOT="/usr/local/go"
    GOTMPDIR=""
    GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    CXX="g++"
    CGO_ENABLED="1"
    GOMOD=""
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"
    PKG_CONFIG="pkg-config"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build543853952=/tmp/go-build -gno-record-gcc-switches"
```

4. Verbose output of running: `golangci-lint run -v`
```
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    Running error: context loading failed: failed to load program with go/packages: go [list -e -json -compiled=true -test=true -export=false -deps=true -find=false -tags selinux seccomp -mod=vendor -- ./...]: exit status 1: build flag -mod=vendor only valid when using modules
```
Is there a way to configure how golangci.com stores repo, or at least set envs? I found `project-path` option in service config, but that will still put repo under $GOPATH. Have you considered absolute paths  there? How to make it work with vendored modules?
