### ISSUE TITLE
govet: fieldalignment check not working

### ISSUE THREAD

**Issue by khatibomar** [golangci/golangci-lint#5845]
### Welcome

- [x] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### How did you install golangci-lint?

Official binary

### Description of the problem

fieldalignment issues are not being reported when using golangci-lint

```console
λ ~/code/playground/nvim/ fieldalignment main.go
/home/ayn/code/playground/nvim/main.go:4:18: struct of size 24 could be 16
λ ~/code/playground/nvim/ golangci-lint run
0 issues.
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 2.1.6 built with go1.24.2 from eabc2638 on 2025-05-04T15:41:19Z
```

</details>

### Configuration

<details>

```console
version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

# Output configuration options
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

# Configure formatters
formatters:
  enable:
    - gofmt
    - goimports

# Configure specific linters
linters-settings:
  govet:
    disable:
      - shadow
    enable:
      - fieldalignment
    settings:
      printf:
        funcs:
          - (log).Printf
          - (log).Fatalf
          - (log).Panicf
          - (*log.Logger).Printf
          - (*log.Logger).Fatalf
          - (*log.Logger).Panicf
          - (slog.Logger).Info
          - (slog.Logger).Error
          - (slog.Logger).Warn
          - (slog.Logger).Debug
          - (*slog.Logger).Info
          - (*slog.Logger).Error
          - (*slog.Logger).Warn
          - (*slog.Logger).Debug

  staticcheck:
    checks: ["all"]

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  unused:
    check-exported: false

  gosec:
    # Available rules: https://github.com/securego/gosec#available-rules
    includes:
      - G101 # Look for hard coded credentials
      - G102 # Bind to all interfaces
      - G103 # Audit the use of unsafe block
      - G104 # Audit errors not checked
      - G106 # Audit the use of ssh.InsecureIgnoreHostKey
      - G107 # Url provided to HTTP request as taint input
      - G108 # Profiling endpoint automatically exposed
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G111 # Potential directory traversal
      - G112 # Potential slowloris attack
      - G114 # Use of net/http serve function that has no support for setting timeouts
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation
      - G203 # Use of unescaped data in HTML templates
      - G204 # Audit use of command execution
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used when creation of file
      - G303 # Creating tempfile using a predictable path
      - G304 # File path provided as taint input
      - G305 # File traversal when extracting zip/tar archive
      - G306 # Poor file permissions used when writing to a file
      - G307 # Deferring a method which returns an error
      - G401 # Detect the usage of weak crypto algorithms
      - G402 # Look for bad TLS connection settings
      - G403 # Ensure minimum RSA key length of 2048 bits
      - G404 # Insecure random number source (rand)
      - G501 # Import blocklist: crypto/md5
      - G502 # Import blocklist: crypto/des
      - G503 # Import blocklist: crypto/rc4
      - G504 # Import blocklist: net/http/cgi
      - G505 # Import blocklist: crypto/sha1
      - G601 # Implicit memory aliasing of items from a range statement
      - G602 # Slice access out of bounds

  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    simple: true
    # Report preallocation suggestions on range loops.
    range-loops: true
    # Report preallocation suggestions on for loops.
    for-loops: false

  sloglint:
    # Use it to disable checks for specific k-v args separated by comma.
    no-printf: err, error

# Enable specific linters
linters:
  disable-all: true
  enable:
    # Default linters for correctness
    - govet # Examines Go source code and reports suspicious constructs
    - staticcheck # Static analysis that's fast, thorough, with low false-positive rate
    - unused # Checks Go code for unused constants, variables, functions and types
    - ineffassign # Detects when assignments to existing variables are not used
    - errcheck # Checks for unchecked errors

    # Security-focused linters
    - gosec # Inspects source code for security problems
    - nilerr # Finds the code that returns nil even if it checks that the error is not nil
    - nilnil # Checks that there is no simultaneous return of nil error and an invalid value
    - bodyclose # Checks whether HTTP response body is closed successfully
    - noctx # Finds sending HTTP request without context.Context
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt are closed properly

    # Performance-focused linters
    - prealloc # Finds slice declarations that could potentially be pre-allocated
    - makezero # Finds slice declarations with non-zero initial length
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative
    - unconvert # Remove unnecessary type conversions
    - wastedassign # Finds wasted assignment statements
    - durationcheck # Checks for two durations multiplied together

    # Code quality linters
    - misspell # Finds commonly misspelled English words
    - gocyclo # Computes and checks the cyclomatic complexity of functions
    - dupl # Detects duplicate code
    - gocognit # Computes and checks the cognitive complexity of functions
    - sloglint # Ensure consistent code style when using log/slog
    - errorlint # Detects problems with error wrapping
    - exhaustive # Check exhaustiveness of enum switch statements
    - loggercheck # Checks key value pairs for common logger libraries (slog)
    - gocritic # Provides diagnostics that check for bugs, performance and style issues
    - dogsled # Checks assignments with too many blank identifiers

# Configure how issues are reported
issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - gosec
        - prealloc

    # Exclude linting issues in generated files
    - path: \.pb\.go
      linters:
        - all
    - path: \.gen\.go
      linters:
        - all
    - path: \.mock\.go
      linters:
        - all

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues created after git revision
  new: false

  # Don't fix found issues automatically
  fix: false
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.24.0 linux/amd64
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/home/ayn/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/home/ayn/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build671072150=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/home/ayn/code/playground/nvim/go.mod'
GOMODCACHE='/home/ayn/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/ayn/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/ayn/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.24.0'
GOWORK=''
PKG_CONFIG='pkg-config'
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO golangci-lint has version 2.1.6 built with go1.24.2 from eabc2638 on 2025-05-04T15:41:19Z
INFO [config_reader] Config search paths: [./ /home/ayn/code/playground/nvim /home/ayn/code/playground /home/ayn/code /home/ayn /home /]
INFO [config_reader] Used config file ../../../.golangci.yaml
INFO [config_reader] Module name "nvim"
INFO maxprocs: Leaving GOMAXPROCS=24: CPU quota undefined
INFO [goenv] Read go env for 2.463683ms: map[string]string{"GOCACHE":"/home/ayn/.cache/go-build", "GOROOT":"/usr/local/go"}
INFO [lintersdb] Active 29 linters: [bodyclose dogsled dupl durationcheck errcheck errorlint exhaustive gocognit gocritic gocyclo gofmt goimports gosec govet ineffassign loggercheck makezero misspell nilerr nilnil noctx perfsprint prealloc sloglint sqlclosecheck staticcheck unconvert unused wastedassign]
INFO [loader] Go packages loading at mode 8767 (imports|types_sizes|compiled_files|deps|exports_file|name|files) took 80.934814ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 178.665µs
INFO [linters_context/goanalysis] analyzers took 0s with no stages
INFO [runner] processing took 2.158µs with stages: exclusion_rules: 397ns, max_same_issues: 352ns, path_absoluter: 242ns, exclusion_paths: 226ns, diff: 124ns, path_relativity: 115ns, max_per_file_from_linter: 114ns, filename_unadjuster: 109ns, path_prettifier: 89ns, source_code: 86ns, max_from_linter: 52ns, nolint_filter: 41ns, invalid_issue: 28ns, fixer: 28ns, path_shortener: 28ns, severity-rules: 26ns, cgo: 26ns, sort_results: 26ns, generated_file_filter: 25ns, uniq_by_line: 24ns
INFO [runner] linters took 289.913783ms with stages: goanalysis_metalinter: 289.890968ms
0 issues.
INFO File cache stats: 0 entries of total size 0B
INFO Memory: 5 samples, avg is 63.4MB, max is 79.7MB
INFO Execution took 373.694278ms
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// Inefficient has a suboptimal memory layout due to field ordering
type Inefficient struct {
	A byte   // 1 byte + 7 bytes padding
	B uint64 // 8 bytes
	C byte   // 1 byte + 7 bytes padding
	D uint32 // 4 bytes + 4 bytes padding
}
```

</details>

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment]
Your configuration is invalid:

```console
$ golangci-lint config verify
jsonschema: "linters" does not validate with "/properties/linters/additionalProperties": additional properties 'disable-all' not allowed
jsonschema: "issues" does not validate with "/properties/issues/additionalProperties": additional properties 'exclude-rules' not allowed
jsonschema: "output" does not validate with "/properties/output/additionalProperties": additional properties 'format', 'print-issued-lines', 'print-linter-name', 'sort-results' not allowed
jsonschema: "" does not validate with "/additionalProperties": additional properties 'linters-settings' not allowed
Failed executing command with error: the configuration contains invalid elements
```


The right configuration is:

<details>

```yml
version: "2"

# Configure formatters
formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign

  # Configure specific linters
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    gosec:
      # Available rules: https://github.com/securego/gosec#available-rules
      includes:
        - G101
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G111
        - G112
        - G114
        - G201
        - G202
        - G203
        - G204
        - G301
        - G302
        - G303
        - G304
        - G305
        - G306
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
        - G601
        - G602
    govet:
      enable:
        - fieldalignment
      disable:
        - shadow
      settings:
        printf:
          funcs:
            - (log).Printf
            - (log).Fatalf
            - (log).Panicf
            - (*log.Logger).Printf
            - (*log.Logger).Fatalf
            - (*log.Logger).Panicf
            - (slog.Logger).Info
            - (slog.Logger).Error
            - (slog.Logger).Warn
            - (slog.Logger).Debug
            - (*slog.Logger).Info
            - (*slog.Logger).Error
            - (*slog.Logger).Warn
            - (*slog.Logger).Debug
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
          - prealloc
        path: _test\.go
      - linters:
          - all
        path: \.pb\.go
      - linters:
          - all
        path: \.gen\.go
      - linters:
          - all
        path: \.mock\.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

```

</details>


```console
$ golangci-lint run          
main.go:4:18: fieldalignment: struct of size 24 could be 16 (govet)
type Inefficient struct {
                 ^
1 issues:
* govet: 1
$ golangci-lint run
main.go:4:18: fieldalignment: struct of size 24 could be 16 (govet)
type Inefficient struct {
                 ^
1 issues:
* govet: 1
```
