### ISSUE TITLE
Much slower than gometalinter after first run

### ISSUE THREAD

**Issue by jonas0616** [golangci/golangci-lint#615]
* Config file: `cat .golangci.yml`
```yaml
linters:
  disable-all: true
  enable:
  ¦ - golint
  ¦ - goimports
  ¦ - govet
service:
  golangci-lint-version: 1.17.x
```

Although golangci-lint is faster than gometalinter in the first run, gometalinter is apparently beat golangci-lint after the first run. It seems that gometalinter can speed up by the build cache. Following is the result run in my project when both of golangci-lint and gometalinter enable `golint`, `goimports`, and `govet`.

| Tool | First Run | Second Run |
| -----|-----------|---------------|
| gometalinter | >20s | <2s |
| golangci-lint | >6s | >6s |

I do know that some linters build SSA representation which required information cannot be found in build cache. But in many cases, we don't need these slow linters.

Especially when it used in integration with editors, only few linters are enabled in order to get immediate feedback. It is really annoying to wait for >6s for every write.
