### ISSUE TITLE
Deadline exceeded: try increase it by passing --deadline option

### ISSUE THREAD

**Issue by javiyt** [golangci/golangci-lint#685]
I'm having problems running the linter, it keeps saying I need to increase the deadline after adding just one file

1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
```
$ golangci-lint --version
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z
```
2. Config file: `cat .golangci.yml`
```
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.17.x # use the fixed version to not introduce new linters unexpectedly

run:
  skip-files:
    - ".*_test\\.go$"
    - ".*_mock\\.go$"
    - ".*\\.pb\\.go$"
  modules-download-mode: vendor

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US
  gocritic: # go-critic docs: https://go-critic.github.io/overview.html
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
      - rangeValCopy
      - paramTypeCombine
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845

linters: # List of available linters: https://github.com/golangci/golangci-lint#enabled-by-default-linters
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
    - lll

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
```
3. Go environment: `go version && go env`
```
$ go version
go version go1.12.9 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS="-mod=vendor"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build222834555=/tmp/go-build -gno-record-gcc-switches"
```
4. Verbose output of running: `golangci-lint run -v`
```
$ golangci-lint run --issues-exit-code 0 -v

level=info msg="[config_reader] Config search paths: [./ /app /]"

level=info msg="[config_reader] Used config file .golangci.yml"

level=info msg="[lintersdb] Active 28 linters: [bodyclose deadcode depguard dupl errcheck gochecknoinits goconst gocritic gocyclo gofmt goimports golint gosec gosimple govet ineffassign interfacer misspell nakedret scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck]"

level=info msg="[lintersdb] Optimized sublinters [staticcheck gosimple unused stylecheck] into metalinter megacheck"

level=info msg="[loader] Go packages loading at mode load types and syntax took 38.823470255s"

level=info msg="[loader] SSA repr building timing: packages building 81.029093ms, total 1.638171099s"

level=info msg="[runner] worker.2 took 17.998486821s with stages: unparam: 8.192296071s, govet: 7.721408338s, gocritic: 1.491882009s, ineffassign: 271.575705ms, deadcode: 124.108204ms, structcheck: 121.933322ms, gocyclo: 61.13468ms, goconst: 9.25056ms, varcheck: 2.844412ms, scopelint: 1.128817ms, nakedret: 752.117µs, gochecknoinits: 74.862µs, typecheck: 5.867µs"

level=info msg="[runner] worker.3 took 18.036323526s with stages: bodyclose: 12.54215085s, goimports: 3.591637287s, gosec: 658.484387ms, gofmt: 525.42312ms, misspell: 436.500905ms, dupl: 199.345935ms, errcheck: 41.647304ms, unconvert: 30.623763ms, depguard: 6.653µs"

level=info msg="[runner] worker.4 took 19.96826041s with stages: golint: 16.090679147s, interfacer: 3.877559338s"

level=info msg="Memory: 269 samples, avg is 217.8MB, max is 1342.3MB"

level=info msg="Execution took 1m9.083424077s"

level=info msg="[runner] worker.1 took 35.46587392s with stages: megacheck: 35.465866949s"

level=info msg="[runner] Workers idle times: #2: 17.369896809s, #3: 17.369836488s, #4: 15.473095775s"

level=info msg="[runner] Issues before processing: 286, after processing: 0"

level=info msg="[runner] processing took 60.660795ms with stages: identifier_marker: 51.084164ms, exclude: 6.622516ms, skip_files: 1.304811ms, autogenerated_exclude: 383.211µs, path_prettifier: 365.147µs, cgo: 304.432µs, skip_dirs: 302.496µs, filename_unadjuster: 267.553µs, nolint: 8.479µs, diff: 3.361µs, source_code: 2.744µs, exclude-rules: 2.386µs, max_same_issues: 2.343µs, max_from_linter: 2.057µs, path_shortener: 2.025µs, max_per_file_from_linter: 1.646µs, uniq_by_line: 1.424µs"

level=info msg="File cache stats: 28 entries of total size 77.9KiB"

level=error msg="Deadline exceeded: try increase it by passing --deadline option"
```
