### ISSUE TITLE
Add support for multiple subdirs each with their own go.mod

### ISSUE THREAD

**Issue by fkautz** [golangci/golangci-lint#828]
Thank you for creating the issue!

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:11:27Z
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
---
run:
  concurrency: 6
  deadline: 15m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - build
    - conf
    - controlplane/scripts
    - forwarder/vppagent/build
    - forwarder/vppagent/conf
    - forwarder/scripts
    - deployments
    - docks
    - scripts
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0.8
  goimports:
    local-prefixes: github.com/networkservicemesh/networkservicemesh
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  misspell:
    locale: US
  unused:
    check-exported: true
  unparam:
    check-exported: true
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-checks:
      - rangeValCopy
      - boolExprSimplify
      - badCond
      - methodExprCall
      - paramTypeCombine
      - ptrToRefParam
      - rangeExprCopy
      - captLocal
      - caseOrder
      - defaultCaseOrder
      - dupBranchBody
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - indexAlloc
      - nestingReduce
      - nilValReturn
      - yodaStyleExpr
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 100
linters:
  disable:
    - depguard
    - wsl
    - lll
    - gofmt
    - varcheck  # deprecated
    - unused  # deprecated
    - goimports
  enable-all: true
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:  # Use relative path from module
    - path: _test\.go
      linters:
        - golint
    - path: integration/const.go
      linters:
        - deadcode
    - path: cmd/admission-webhook/init.go
      linters:
        - gochecknoglobals
        - gochecknoinits
    - path: cmd/nsm-coredns
      linters:
        - gochecknoglobals
        - gochecknoinits
    - path: tools/socket.go
      linters:
        - gochecknoglobals
        - gochecknoinits
        - gosec
    - path: pkg/monitor/
      linters:
        - dupl
    - path: pkg/nsm.nsm.go
      linters:
        - gocyclo  # TODO: reduce nsm.request() complexity
    - path: cloudtest/pkg/utils/process.go
      linters:
        - gosec
    - path: cloudtest/pkg/commands/main.go
      linters:
        - gosec
        - funlen
    - path: probes/health/serve_mux_health.go
      linters:
        - gosec
    - path: kubetest/log_utils.go
      linters:
        - gosec
  exclude:
    - should not use dot imports
    - \`version\` is a global variable
    - not declared by package utf8
    - lines are duplicate of```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
go version go1.13.1 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fkautz/Library/Caches/go-build"
GOENV="/Users/fkautz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fkautz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fkautz/src/networkservicemesh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4g/mwsmt1wj5qd5dwdhrshkfwzw0000gn/T/go-build534044314=/tmp/go-build -gno-record-gcc-switches -fno-common"```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/fkautz/src/networkservicemesh /Users/fkautz/src /Users/fkautz /Users /] 
INFO [lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck] 
INFO [loader] Go packages loading at mode 575 (imports|exports_file|deps|files|name|types_sizes|compiled_files) took 148.047143ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 252.334µs 
INFO [runner] processing took 2.757µs with stages: max_same_issues: 464ns, autogenerated_exclude: 446ns, nolint: 288ns, max_from_linter: 181ns, skip_dirs: 178ns, path_prettifier: 175ns, filename_unadjuster: 164ns, cgo: 129ns, identifier_marker: 115ns, skip_files: 112ns, source_code: 108ns, path_shortener: 105ns, diff: 101ns, max_per_file_from_linter: 50ns, uniq_by_line: 48ns, exclude: 47ns, exclude-rules: 46ns 
INFO [runner] linters took 79.834664ms with stages: goanalysis_metalinter: 49.130728ms, unused: 30.658834ms 
INFO File cache stats: 0 entries of total size 0B 
INFO Memory: 4 samples, avg is 70.1MB, max is 70.9MB 
INFO Execution took 243.209356ms                  ```

</details>

Network Service Mesh (a CNCF sandbox project) is currently using multiple subdirs each with their own go.mod and go.sum.

E.g.

```
./go.mod
./go.sum
forwarder/go.mod
forwarder/go.sum
k8s/go.mod
k8s/go.sum
```

When we run golangci-lint, only the root is loaded and all subdirs with their own go.mod are ignored. I assume this is to avoid analyzing vendored code. Unfortunately, this behavior prevents our repository from being fully analyzed in golangci.com.

Please add support for multiple subdirs to be listed recursively. We are ok adding these to the .golangci.yml if necessary.

Thanks for building such a great tool! Cheers!

**Comment by kpurdon** [comment]
To add a bit of color here, this is a common issue for anybody with a multi-module monorepo (a reasonably common pattern).

Given the following directory structure:
```
monorepo/
├── bar
│   ├── bar.go
│   └── go.mod
├── foo
│   └── foo.go
└── go.mod
```

Running the following from the root of `monorepo` `golangci-lint run ./foo ./bar` will fail on `./bar` w/ the error `ERRO Running error: context loading failed: no go files to analyze`.

**Comment by twelho** [comment]
I came up with the following solution when trying to set up the [golangci-lint GitHub Action](https://github.com/marketplace/actions/run-golangci-lint) for a monorepo:

`$ cat .github/workflows/golangci-lint.yaml`
```yaml
name: golangci-lint
on: [push, pull_request]
jobs:
  resolve-modules:
    name: Resolve Modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - id: set-matrix
        run: ./tools/resolve-modules.sh
  golangci:
    name: Linter
    needs: resolve-modules
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
          working-directory: ${{ matrix.workdir }}
```

`$ cat ./tools/resolve-modules.sh`
```bash
#!/bin/bash
# Recursively finds all directories with a go.mod file and creates
# a GitHub Actions JSON output option. This is used by the linter action.

echo "Resolving modules in $(pwd)"

PATHS=$(find . -mindepth 2 -type f -name go.mod -printf '{"workdir":"%h"},')
echo "::set-output name=matrix::{\"include\":[${PATHS%?}]}"
```

This uses the [newly introduced](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/) `fromJson()` to dynamically define a matrix strategy for each directory that contains a `go.mod` file (excluding top-level) and runs golangci-lint in each of those directories (submodules) separately. Less ideal than having official support for multi-module monorepos, but at least it doesn't require defining a configuration for each submodule separately.

**Comment by matrixik** [comment]
Adding to @twelho (thank you for this!)
Use:
```bash
PATHS=$(find . -mindepth 2 -not -path "*/vendor/*" -type f -name go.mod -printf '{"workdir":"%h"},')
```
to exclude `vendor` folders from linting.

**Comment by sakirma** [comment]
I still have a problems with multiple modules within my repo.
@twelho 's solution did solve my problem! 

changing
`uses: golangci/golangci-lint-action@v1`
to
`uses: golangci/golangci-lint-action@v2`
Made it all work again.

**Comment by franklinkim** [comment]
Hi, any update if this will be a supported without workarounds?

**Comment by gnuletik** [comment]
For `pre-commit` users, you can define multiple entries until a flag into golangci-lint is implemented.

```yaml
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
      # no built-in support for multiple go.mod
      # https://github.com/golangci/golangci-lint/issues/828
      - id: golangci-lint
        name: golangci-lint-root
        entry: bash -c 'golangci-lint run'

      - id: golangci-lint
        name: golangci-lint-subdir
        entry: bash -c 'cd subtest && golangci-lint run --config $OLDPWD/.golangci.yml'
```

**Comment by JoelOtter** [comment]
Any movement on this?

**Comment by wafer-bw** [comment]
Checking in, hoping this can be supported soon.

`actions/setup-go` already supports multi-module seen [here](https://github.com/actions/setup-go/issues/371).

**Comment by wafer-bw** [comment]
[This](https://stackoverflow.com/a/68746128) worked for me.

```yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [module1, module2, module3]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.1'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          working-directory: ${{ matrix.directory }}
```

**Comment by gaby** [comment]
@wafer-bw Thank you for the suggestion. I was able to make it dynamic by using the following:


```yaml
name: golangci-lint

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          DIRECTORIES=$(find . -type d -not -path '*/\.*' | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${DIRECTORIES}" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.modules }}
```

**Comment by stevenh** [comment]
I was surprised that this didn't work out the box and was hiding issues because of multiple modules in the repo with no warning, definitely a gotach.

**Comment by ldez** [comment]
duplicate of #74

**Comment by stevenh** [comment]
This says a duplicate of #74 but that was merged 5years ago yet this was still present in the last month, wrong reference @ldez ?

**Comment by JoelOtter** [comment]
Yes I think 74 is not related to this issue

**Comment by ldez** [comment]
Sorry It was an issue and repository confusion with https://github.com/golangci/golangci-lint-action/issues/74

**Comment by ldez** [comment]
I added examples for Go workspace and the GitHub Action: https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use

**Comment by stevenh** [comment]
This will be helpful for actions but doesn't seem to solve the local run issue, did I miss something?

The examples also states go workspace but doesn't mention a workspace requirement, is it a requirement?

**Comment by chudilka1** [comment]
That is what worked for me:
```yaml
- name: Set Modules for GolangCI Lint
        id: set-modules
        run: | 
          PATHS_TO_GO_MOD=$(find . -type f -name go.mod | awk -F'/go.mod' '{if ($1 == ".") print "./"; else print $1}')
          PATHS_TO_GO_MOD_JSON=$(echo "$PATHS_TO_GO_MOD" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${PATHS_TO_GO_MOD_JSON}" >> $GITHUB_OUTPUT
```
Thanks for guiding me in the right direction.

**Comment by krhubert** [comment]
Let me share my approach. It uses makefile with `cd` into each submodule.
 
```make
# each directory of a submodule in the go workspace.
# go commands provide no built-in way to get all workspace submodules.
#
# Make sure paths are relative to the current directory, so the output
# of other commands is shorter and more readable.
submodules := $(shell go list -f '{{.Dir}}' -m | xargs -I {} realpath --relative-to=. {})

.PHONY: golangci/lint
golangci/lint:: ## run golangci-lint for all submodules
define golangci/lint-target
    golangci/lint:: ; cd $1 && golangci-lint run --path-prefix $1 ./...
endef
$(foreach mod,$(submodules),$(eval $(call golangci/lint-target,$(mod))))
```

```bash
repo ➜ make golangci/lint
cd experiment && golangci-lint run ./...
0 issues.
cd service && golangci-lint run ./...
0 issues.
cd shared && golangci-lint run ./...
0 issues.
cd tools/migrate && golangci-lint run ./...
tools/migrate/cmd/migrate/main.go:9:1: File is not properly formatted (gci)
```

It would be great to have a flag like `run -gowork ./...` (or some better name) which does the same thing as this script and  merge all outputs into single one.

**Comment by Glitchy-Sheep** [comment]
Fun fact: the whole linter doesn't work in VSCode if the workspace is set to a Go workspace folder:

<img width="1011" height="127" alt="Image" src="https://github.com/user-attachments/assets/e5d99f70-97e8-4f7a-b8b9-b5a9b9c2097d" />


**So I basically don't have a linter at all** if I want to work from that workspace (because it fails at an early stage).

Guys, that's *very* inconvenient. I have to open a separate VSCode workspace for **each module** I want to work on if I want the linter to work.

So it's not just a CI problem.

**Comment by mauriciabad** [comment]
@Glitchy-Sheep did you find a solution to make VS Code work? 

I can't even run `golangci-lint run ./backend/...` from the terminal.

**Comment by Glitchy-Sheep** [comment]
Hi @mauriciabad, kind of - I open the whole monorepo first, then drag and drop the needed packages into my VS Code workspace. I use the root to observe and the packages to code, mainly because of the built-in linter integration.  

If you just need to run `golangci-lint` per module, the scripts above in the thread are fine.

**UPD**: Ah, and this doesn’t work in the terminal because VS Code does essentially the same thing - it just runs the binary the same way you would manually. So the effect is identical.

**Comment by mauriciabad** [comment]
@Glitchy-Sheep Playing around I found a temporary solution, maybe it works for you too. https://github.com/golangci/golangci-lint/issues/6110#issuecomment-3368974420

```jsonc
// .vscode/settings.json
{
  "go.lintOnSave": "package"
}
```

**Comment by yeldiRium** [comment]
If anyone found this issue while trying to get golingci-lint to work in a monorepo with pre-commit, I wanna share my working setup.
I've added a custom hook to .pre-commit-config.yaml:
```yaml
repos:
- repo: local
  hooks:
  - id: "golangci-lint-monorepo"
    name: "golangci-lint-monorepo"
    entry: "./scripts/golangci-lint-monorepo"
    files: "\\.go$"
    language: "system"
    require_serial: true
```

And added the corresponding bash script under `./scripts/golangci-lint-monorepo`:
```bash
#!/usr/bin/env bash
set -e

for dir in $(echo "$@" | xargs -n1 dirname | sort -u); do
	cd "${dir}"
	golangci-lint run
	cd -
done
```

<details><summary>Edit: More complex script that first lints everything, then determines exit code</summary>
<p>

```bash
#!/usr/bin/env bash

errors=0
for dir in $(echo "$@" | xargs -n1 dirname | sort -u); do
  cd "''${dir}"
  if ! ${lib.getExe pkgs.golangci-lint} run; then
    ((errors += 1))
  fi
  cd -
done

if [[ $errors -gt 0 ]]; then
  exit 1
fi
```

</p>
</details> 


I would much appreciate it and this would be much easier if golangci-lint would respect the nearest go.mod instead.
