### ISSUE TITLE
pre-release for Go 1.14

### ISSUE THREAD

**Issue by pierrre** [golangci/golangci-lint#962]
Hello,
Is it possible to have a pre-release (maybe a beta) for Go 1.14 ?
It seems that the pre-compiled binaries are not compatible with Go 1.14rc1.

**Comment by ernado** [comment]
Hey, I'm planning an alpha release compiled with go1.14rc1 until Friday.

**Comment by ernado** [comment]
Seems it is non-trivial to do it in automated way via our CI/CD.

**Comment by tpounds** [comment]
@ernado, @pierrre I've updated the `.travis.yml` to build against Go `1.14rc1` in #964. However, https://github.com/golangci/golangci-lint/blob/master/.travis.yml#L34 needs to be updated to to `1.14+` before new a release will be built that supports the version. @pierrre Have you tried installing via `go get` now that #930 has been merged?

**Comment by pierrre** [comment]
Thank you, but I have another very strange error:
```
ERRO Running error: failed to pre-run govet: failed to configure analyzers: settings key "printf" must be valid analyzer name, valid analyzers: [asmdecl assign atomic atomicalign bools buildtag cgocall composites copylocks deepequalerrors errorsas findcall httpresponse loopclosure lostcancel nilfunc nilness shadow shift sortslice stdmethods structtag tests unmarshal unreachable unsafeptr unusedresult]
```

My config:
```yaml
run:
  timeout: "10m"
linters:
  disable-all: true
  enable:
    - "bodyclose"
    - "deadcode"
    - "depguard"
    - "errcheck"
    - "gocritic"
    - "gocyclo"
    - "gofmt"
    - "goimports"
    - "golint"
    - "govet"
    - "ineffassign"
    - "megacheck"
    - "misspell"
    - "nakedret"
    - "structcheck"
    - "unconvert"
    - "unparam"
    - "varcheck"
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors
      - reflect
      - unsafe
      - github.com/pkg/errors
  gocyclo:
    min-complexity: 10
  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - "(github.com/xxx/golang-libraries/errors).Newf"
          - "(github.com/xxx/golang-libraries/errors).WithMessagef"
          - "(github.com/xxx/golang-libraries/errors).Wrapf"
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
```

I think I've already mentioned this issue somewhere.
It's due to a recent change in x/tools (the config of the govet linter)
